cardano-foundation/CIPs

CIP3/Byron.md, CIP3/CIP3.md, CIP3/Icarus.md, CIP3/Ledger.md
This CIP is meant to describe (with test vectors) all the possible root key derivation strategies used in Cardano up to now. Efforts have been done to document this before such as [https://github.com/satoshilabs/slips/blob/master/slip-0023.md](SIP-0023), but it last a reference implementation and also doesn't address Ledger or Trezor generation.
=> CIP3 - Wallet key generation

CIP-0010/CIP-0010.md
Requesting reservation of 6770 for the metadata related to the Coconut Pool Fortune Teller (fortunes.coconutpool.com)
=> Requesting reservation of 6770

CIP-0010/CIP-0010.md, CIP-0015/CIP-0015.md, CIP-Registration/CIP-Registration.md
This CIP just described the format that was used during the round 2 registration for Catalyst. No guarantee IOHK will continue to use this system going forward, but since many explorers, wallets & tools have hardcoded support for this specific registrartion format, I felt it was appropriate to document this properly as a CIP
=> Catalyst Registration transaction metadata format

CIP-0010/CIP-0010.md, CIP-0010/registry.json, CIP-0010/registry.schema.json
I would like to propose to include a machine readable JSON file that contains the registry. Our project needs to list these as description and it is not easy to parse from markdown :)
I did not include the reserved places, which I assume are fixed within the CIP right now.
=> CIP-0010: add support for registry.json

CIP-0015/CIP-0015.md, CIP-0015/schema.cddl
Following up on https://github.com/cardano-foundation/CIPs/pull/79#discussion_r612274272 by @KtorZ
=> CIP-0015: put CDDL schema into a separate file

CIP-0006/CIP-0006.md, package-lock.json, package.json, scripts/build.js
Hey guys, this is a a fix attempt to satisfy Netlify CI pipeline when trying to deploy pr #21 as it is failing when trying to retrieve the authors section for some reason.
Also removed an outdated handlebars plugin related to date formatting and just replaced with a moment js solution.
`CIP-0006` also caused some build failures due to it having some extra comments in the `Created` field in the markdown file while handlebars try to pass it to the momentjs date format function.
=> CI Fallback and Updates

CIP-0020/CIP-0020.md
after the approval and the merge into master, i think this CIP can also be switched to active. we also have added CNFT.io as an implementation partner into the list.
=> switching CIP-0020 to 'Active'

CIP-0007/README.md
Proposed.
I understand that a better solution might be to apply the a0 pledge benefit fully and only to the pledge and not to the total stake.
I am attempting to move this CIP to Porposed in order to have IOG respond with their plans in regards to the a0 pledge benefit factor.
=> CIP-0007 to Proposed

CIP-0002/README.md
For the sake of consistency align headers with all other CIPs. (start with H2)
=> Align headers with other CIP (start with H2)

CIP-0009/README.md
=> CIP9: typo

CIP-0033/README.md
was creating issue with cips.cardano.org
=> adjusting type

CIP-0005/README.md
CIP type was 'Active' but it should be 'Standards'
=> Fixing Type

CIP-0021/README.md
This PR updates CIP-0021 with multi-sig changes. The updated Ledger Cardano app should be released in the upcoming days. Trezor with multi-sig support will be released on December 8th.
=> CIP-0021 | Add multisig changes

CIP-0015/README.md
I noticed there was no reference implementation for CIP15 so I created one
=> Add reference implementation for CIP15

CIP-0023/README.md
Note that with the price of ADA being 2x what it was when I proposed this CIP, it is even more critical to adopt this CIP or to prepay min fees.
=> Fair min fees

README.md
(And thus consequently, on the generated website front-page.)
There seems to be a lot of confusion in the community about what CIPs are and what stages they go through. So I hope that these few lines will explain a bit better the situation and gives a clearer view of the bigger picture.
=> Add more details on main's README

CIP-0021/README.md
This PR updates CIP-0021 with Alonzo/Plutus changes. The exact release date of the updated Ledger app is not yet clear but it should be within a month. Trezor update will potentially be released in April - if Trezor will do an April release.
=> CIP-0021 | Add Alonzo changes

CIP-0003/README.md, CIP-0035/README.md
fixing links identified in issue https://github.com/cardano-foundation/CIPs/issues/109#issuecomment-1173872165 - any more please add here.
=> Broken links in various CIPs

CIP-0055/README.md
posted here (in original CIP PR): https://github.com/cardano-foundation/CIPs/pull/265#discussion_r914388822
=> CIP-0055 correction: spelling error

CIP-0027/README.md
Fix https://github.com/cardano-foundation/CIPs/pull/184
=> CIP-0027 | Fix status header

CIP-0001/README.md, README.md
- :round_pushpin: **Update merged, reviewed and stalled CIPs from top-level README.**
- :round_pushpin: **Update editors list to reflect current state**
Removed Duncan (as discussed with him), and added Robert to the list within CIP-0001.
=> Top-Level README Chore / Editors List Update

README.md
These weren't yet uploaded the last time I edited this material (https://github.com/cardano-foundation/CIPs/pull/305#issue-1316113659); found this channel through CIP Editors' Discord dialogue this week 🤓
=> top README: link to meeting recordings

CIP-0030/README.md
Fix a small typo within the readme file
=> CIP-0030 | Fix some spelling errors

CIP-0010/registry.json
Registering transaction metadatum label for Finitum.io token bridge txs.
=> CIP-0010 Finitum.io token bridge txs metadata

CIP-0009/README.md, CIP-0028/README.md, CIP-0055/README.md, README.md
- :round_pushpin: **Turn CIP-0060 as active in the top-level README.**
- :round_pushpin: **Turn CIP-0055 as 'active', rename CIP-0009, CIP-00028 & CIP-0055 for clarity, and link them together.**
- :round_pushpin: **Add new proposals from triage to the top-level README table**
=> Editors meeting #57 housekeeping

CIP-0002/README.md
=> Adjust preamble and structure of CIP-0002 to abide by new CIP-0001

CIP-0004/README.md, README.md
=> Adjust CIP-0004 w.r.t new CIP-0001 structure

CIP-0003/README.md
=> CIP-0003 | adjust preamble and structure wrt CIP-0001

.github/CIP-TEMPLATE.md, .github/CPS-TEMPLATE.md, CIP-0001/README.md
Found that these were missing as I updated a few past CIPs.
=> CIP/CPS template & categories tweaks 

CIP-0026/schema.json
Field `signatures` should be an array to support multiple attestation signatures on entries.
=> CIP-0026 | Update signatures schema

.github/CIP-TEMPLATE.md, .github/CPS-TEMPLATE.md, CIP-0001/README.md, CIP-0002/README.md, CIP-0003/README.md, CIP-0004/README.md, CIP-0005/README.md, CIP-0013/README.md, CIP-0020/README.md, CIP-0031/README.md, CIP-0032/README.md, CIP-0033/README.md
=> Rework CIP-0005's headers and sections + remove h1 headers from various CIPs

CIP-0033/README.md
=> CIP-0033 | Typo in README

CIP-0059/feature-table.md
I find this table very useful both for myself and for pointing others to it.
=> CIP-0059 | Add "Valentine" HF

CIP-0058/README.md
=> CIP-0058 | Fix metadata in preamble

CIP-0057/README.md
Fix Aiken link (results in 404)
=>  CIP-0057 | Fix Aiken link

README.md
Note: I also went ahead and assigned numbers to the various dangling CPS that were opened and reviewed in the past but somehow slipped through. 
Also, CIP-0094 & CPS-0005 are now merged as they had been discussed and approved already.
=> Refresh README.

CIP-1694/README.md, README.md
We're heading into the age of Voltaire, laying down the foundations for decentralized decision-making. This CIP describes a mechanism for on-chain governance that will underpin the Voltaire phase of Cardano. The document builds on and extends the original Cardano governance scheme that was based on a fixed number of governance keys. It aims to provide a first step that is both valuable and technically achievable in the near term as part of the proposed Voltaire governance system.
It also seeks to act as a jumping-off point for continuing community input, including on appropriate threshold settings and other on-chain settings. Subsequent proposals may adapt and extend this proposal to meet emerging governance needs.
--- 
See [rendered …
=> CIP-1694? | A First Step Towards On-Chain Decentralized Governance

CIP-0023/README.md
=> CIP-0023 | Adjust preamble and structure w.r.t CIP-0001

CIP-0052/README.md
We are operating in the auditing business on Cardano for some time already. Please add us to the table.
=> CIP-0052 | Add Vacuumlabs to the list of auditors

CIP-0001/README.md, README.md
Hello,
My name is Adam Dean. I am the co-founder of Buffy Bot Publishing, NFTxLV (formerly cNFTcon), Drip Dropz and several other projects and initiatives on the Cardano blockchain. I am a co- or principal author of several CIPs and am passionate about bringing well-defined standards to the Cardano ecosystem.
I am humbly nominating myself to serve as one of our community CIP Editors moving forward in the future to help shoulder some of the burden.
I am happy to answer any questions, comments, or concerns that you may have prior to my acceptance.
=> CIP Editor Nomination: Adam Dean

CIP-1694/README.fr.md
* Added acknowledgement of workshop participants to the french version README.fr.md
* Reference
- Pull request #571 
- Revision 729bf52
=> CIP1694 | Add acknowledgement of workshop participants in French

CIP-1694/README.md
Full list of acknowledgements for community workshops
=> CIP-1694 | Add acknowledgements for community workshops

CIP-1694/README.fr.md
- Added the 2nd list of acknowledgements for the french translation.
From pull request (#578)
revision 430f64d
=> CIP-1694 | Add acknowledgements for community workshops in French

CIP-0002/README.md, CIP-0003/README.md
- Fixed Adrestia documentation link.
- Added two missing full stops.
=> Fix or rationalise Adrestia links

README.md
Progressing CIPs 101 (keccak https://github.com/cardano-foundation/CIPs/pull/524: merged) and 102 (royalty tokens https://github.com/cardano-foundation/CIPs/pull/551: number assigned)
=> Update top-level README: meeting #72 promotions

CIP-0095/README.md, README.md
apologies for making a separate PR for this: I was going to sneak it in before merging https://github.com/cardano-foundation/CIPs/pull/509 but thought we had other name changes to make as per https://github.com/cardano-foundation/CIPs/pull/594 (these were only PRs & not CIP candidates). 😖
=> Update top-level README: meeting #73 promotion

README.md
New CIP candidate:
- https://github.com/cardano-foundation/CIPs/pull/597
and CPS candidates:
- https://github.com/cardano-foundation/CIPs/pull/605
- https://github.com/cardano-foundation/CIPs/pull/611
=> Update top-level README: post meeting #76

README.md
... in advance of anticipated social discussion as per @Crypto2099 https://github.com/cardano-foundation/CIPs/pull/467#issuecomment-1817035594.
=> Update top-level README: rush new title for CIP-0088

README.md
Promoted to candidate:
- https://github.com/cardano-foundation/CIPs/pull/617
- https://github.com/cardano-foundation/CIPs/pull/635
- https://github.com/cardano-foundation/CIPs/pull/632
Merged:
- https://github.com/cardano-foundation/CIPs/pull/467
- https://github.com/cardano-foundation/CIPs/pull/546
- https://github.com/cardano-foundation/CIPs/pull/556
=> Update top-level README: post meeting #78

CIP-0006/README.md
Fixes #644.
([edited version](https://github.com/rphair/CIPs/blob/remediate-0006/CIP-0006/README.md))
=> CIP-0006 | Adjust preamble and structure w.r.t CIP-0001

CIP-0026/README.md
Fixes #671.
@KtorZ @michaelpj @polinavino this is such a well documented, apparently broadly useful proposal... were there really never any implementations of it besides [offchain-metadata-tools](https://github.com/input-output-hk/offchain-metadata-tools)?  Could there in turn have been anything that included `offchain-metadata-tools` to provide some commercial or community implementation?
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0026/CIP-0026/README.md))
=> CIP-0026 | Adjust preamble and structure w.r.t CIP-0001

CIP-0042/README.md
Fixes #697.
@KtorZ @ch1bo since https://github.com/cardano-foundation/CIPs/pull/218#discussion_r849660648 was never resolved (and I'm not seeing any documentation for this structure outside this CIP) I'm leaving that box unchecked on _Path to Active_ even though this is obviously `Active`.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0042/CIP-0042/README.md))
=> CIP-0042 | Adjust preamble and structure w.r.t CIP-0001

CIP-1855/README.md
Fixes #728.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-1855/CIP-1855/README.md))
=> CIP-1855 | Adjust preamble and structure w.r.t CIP-0001

CIP-0019/README.md
Fixes #663.
([edited proposal](https://github.com/rphair/CIPs/blob/remediate-0019/CIP-0019/README.md))
=> CIP-0019 | Adjust preamble and structure w.r.t CIP-0001

CIP-1854/README.md
Fixes #726.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-1854/CIP-1854/README.md))
=> CIP-1854 | Adjust preamble and structure w.r.t CIP-0001

CIP-0018/README.md
Fixes #642.
([edited version](https://github.com/rphair/CIPs/blob/remediate-0018/CIP-0018/README.md))
=> CIP-0018 | Adjust preamble and structure w.r.t CIP-0001

CIP-0020/README.md
Fixes #410.
([edited version](https://github.com/rphair/CIPs/blob/remediate-0020/CIP-0020/README.md))
=> CIP-0020 | Adjust preamble and structure w.r.t CIP-0001

CIP-0011/README.md
Fixes #653.
**Note** this lists `Implementors: NA` because it is hard to conceive of a list of implementors when adoption has been universal.
([edited proposal](https://github.com/rphair/CIPs/blob/remediate-0011/CIP-0011/README.md))
=> CIP-0011 | Adjust preamble and structure w.r.t CIP-0001

CIP-0012/README.md
Fixes #655.
([edited proposal](https://github.com/rphair/CIPs/blob/remediate-0012/CIP-0012/README.md))
=> CIP-0012 | Adjust preamble and structure w.r.t CIP-0001

CIP-0014/README.md
Fixes #657.
As in other universally adopted, long-`Active` CIPs I've put `Implementors: NA` which is of course open to discussion & amendment.
([edited proposal](https://github.com/rphair/CIPs/blob/remediate-0014/CIP-0014/README.md))
=> CIP-0014 | Adjust preamble and structure w.r.t CIP-0001

CIP-0021/README.md
Fixes #665.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0021/CIP-0021/README.md))
=> CIP-0021 | Adjust preamble and structure w.r.t CIP-0001

CIP-0022/README.md
Fixes #667.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0022/CIP-0022/README.md))
=> CIP-0022 | Adjust preamble and structure w.r.t CIP-0001

CIP-0029/README.md
Fixes #677.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0029/CIP-0029/README.md))
=> CIP-0029 | Adjust preamble and structure w.r.t CIP-0001

CIP-0031/README.md
Fixes #682.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0031/CIP-0031/README.md))
=> CIP-0031 | Adjust preamble and structure w.r.t CIP-0001

CIP-0032/README.md
Fixes #684.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0032/CIP-0032/README.md))
=> CIP-0032 | Adjust preamble and structure w.r.t CIP-0001

CIP-0033/README.md
Fixes #686.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0033/CIP-0033/README.md))
=> CIP-0033 | Adjust preamble and structure w.r.t CIP-0001

CIP-0034/README.md
Fixes #689.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0034/CIP-0034/README.md))
=> CIP-0034 | Adjust preamble and structure w.r.t CIP-0001

CIP-0049/README.md
Fixes #699.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0049/CIP-0049/README.md))
=> CIP-0049 | Adjust preamble and structure w.r.t CIP-0001

CIP-0054/README.md
Fixes #704.
@kieransimkin I have proposed that your _Description_ at the beginning is really the _Rationale_ as required by our modern CIP standard.  Also I've proposed a _Path to Active_ that could be used to demonstrate `Active` status if you are [still working on this](https://forum.cardano.org/t/cip-draft-cardano-smart-nfts/100470/36).
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0054/CIP-0054/README.md))
=> CIP-0054 | Adjust preamble and structure w.r.t CIP-0001

CIP-0060/README.md
Fixes #710.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0060/CIP-0060/README.md))
=> CIP-0060 | Adjust preamble and structure w.r.t CIP-0001

CIP-0067/README.md
Fixes #712.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0067/CIP-0067/README.md))
=> CIP-0067 | Adjust preamble and structure w.r.t CIP-0001

CIP-0071/README.md
Fixes  #716.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0071/CIP-0071/README.md))
=> CIP-0071 | Adjust preamble and structure w.r.t CIP-0001

CIP-0381/README.md
Fixes #718.
@michaelpj @iquerejeta I had thought this CIP was well on the way to `Active` by now but so far nobody has suggested this to the CIP repository.  It seemed like costing and other prerequisites were proceeding as per expectations in CIP35.
- Did that ever follow through into a release in Plutus, and if so should we merge this current update as `Active`?
- In any case: does the _Path to Active_ here accurately, and in enough detail, suggest whatever official steps that have been taken & whatever might remain to be done?
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0381/CIP-0381/README.md))
=> CIP-0381 | Adjust preamble and structure w.r.t CIP-0001

CIP-1852/README.md
Fixes #722.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-1852/CIP-1852/README.md))
=> CIP-1852 | Adjust preamble and structure w.r.t CIP-0001

CIP-1853/README.md
Fixes #724.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-1853/CIP-1853/README.md))
=> CIP-1853 | Adjust preamble and structure w.r.t CIP-0001

CIP-0025/README.md
Fixes #669.
@SmaugPool @alessandrokonrad I cannot imagine, after all the water under this bridge, trying to enumerate the implementors of this CIP... hence the 'Implementors: NA' in the header, which I've had to designate to proposals remediated in #389 which have been `Active` since the "early days".  If you have a better way of defining the implementation scope, please free free to post it here.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0025/CIP-0025/README.md))
=> CIP-0025 | Adjust preamble and structure w.r.t CIP-0001

CIP-0095/README.md, README.md
- Updated to reflect author's new email address
- Added implementer
- Updated links throughout to reflect core cardano code moving to Intersect
- Updated `Acceptance Criteria`
- Updated `Path to Active`
- Updated CIP status to `active` in line with updated `Acceptance Criteria`
=> CIP-0095 | Promote CIP and update links

README.md
merged:
- https://github.com/cardano-foundation/CIPs/pull/395
promoted to CIP candidate:
- https://github.com/cardano-foundation/CIPs/pull/641
- https://github.com/cardano-foundation/CIPs/pull/679
=> Update top-level README: post meeting #79

README.md
Promoted to CIP candidate:
- https://github.com/cardano-foundation/CIPs/pull/733
- https://github.com/cardano-foundation/CIPs/pull/749
Promoted to CPS candidate:
- https://github.com/cardano-foundation/CIPs/pull/625
- https://github.com/cardano-foundation/CIPs/pull/742
=> Update top-level README: post meeting #80

README.md
Merges:
- https://github.com/cardano-foundation/CIPs/pull/742
- https://github.com/cardano-foundation/CIPs/pull/638
=> Update top-level README: post meeting #82

CIP-0095/README.md, CIP-0105/README.md, CPS-0010/README.md
- Reflect new optional sections for acknowledgements in CIPs/CPSs
- Update author's email address
- Reflect new Copywright section and License header for CPS
=> CIP-95, CIP-105, CPS-10 | Update CIPs/CPSs to reflect new optional sections + update email

README.md
New candidate:
- https://github.com/cardano-foundation/CIPs/pull/788
=> Update top-level README: post meeting #85

README.md
Merges:
- https://github.com/cardano-foundation/CIPs/pull/632
=> Update top-level README: post meeting #86

README.md
promotions:
- https://github.com/cardano-foundation/CIPs/pull/796
=> Update top-level README: post meeting #87

CIP-0010/registry.json
Added metadata label for DAO bootstrap metadata performed via [clarity.vote](https://www.clarity.vote/) platform
=> CIP-0010 | Add Clarity (DAO creation) metadata label

CIP-1694/README.md
This mostly aligns the description of the Bootstrap phase with what we're actually going to do. Additionally, it fixes some other small things that people have noticed.
=> CIP-1694 | Bootstrap & other fixes

README.md
Promotions:
- https://github.com/cardano-foundation/CIPs/pull/624
- https://github.com/cardano-foundation/CIPs/pull/806
Merges:
- https://github.com/cardano-foundation/CIPs/pull/588
- https://github.com/cardano-foundation/CIPs/pull/749
- https://github.com/cardano-foundation/CIPs/pull/766
Deprecations:
- https://github.com/cardano-foundation/CIPs/pull/296
- https://github.com/cardano-foundation/CIPs/pull/309
Corrections:
- Fixed link from CPS-0010 which pointed to CPS-0007
=> Update top-level README: post meeting #88

README.md
Merges:
- https://github.com/cardano-foundation/CIPs/pull/587
- https://github.com/cardano-foundation/CIPs/pull/788
=> Update top-level README: post meeting #89

CIP-0058/README.md
As per [this request here](https://github.com/cardano-foundation/CIPs/pull/825#issuecomment-2137044650).
=> CIP-0058 | Add supersession note

README.md
Merges:
- https://github.com/cardano-foundation/CIPs/pull/747
- https://github.com/cardano-foundation/CIPs/pull/624
- https://github.com/cardano-foundation/CIPs/pull/806
Promotions:
- https://github.com/cardano-foundation/CIPs/pull/825
- https://github.com/cardano-foundation/CIPs/pull/488
- https://github.com/cardano-foundation/CIPs/pull/832
CIP-0125? title still under review; see https://github.com/cardano-foundation/CIPs/pull/832#pullrequestreview-2111101780
p.s. also fixed spelling mistake inherited from document & PR title of #617.
=> Update top-level README: post meeting #90

README.md
Merges:
- https://github.com/cardano-foundation/CIPs/pull/617
- https://github.com/cardano-foundation/CIPs/pull/825
Promotions:
- https://github.com/cardano-foundation/CIPs/pull/841
Waiting for author (coincidental; unrelated to meeting discussion):
- https://github.com/cardano-foundation/CIPs/pull/441
=> Update top-level README: post meeting #91

README.md
Merges:
- https://github.com/cardano-foundation/CIPs/pull/635
Promotions:
- https://github.com/cardano-foundation/CIPs/pull/628
- https://github.com/cardano-foundation/CIPs/pull/826
Also @Ryun1 @Crypto2099 in light of https://github.com/cardano-foundation/CIPs/pull/854 I've compared all statuses listed in the top level `README` with the document statuses & found a bunch of them out of sync... generally from #389 which didn't update the table in each descendant PR branch.  I've kept these in a separate (the first) commit so they can be read separately for confirmation.
=> Update top-level README: post meeting #92, including status review

CIP-1694/README.fr.md
- Correction to the French version related to PR #847
=> CIP-1694 | French - Updates and semantics

README.md
Merged:
- https://github.com/cardano-foundation/CIPs/pull/841
Promoted:
- https://github.com/cardano-foundation/CIPs/pull/758
- https://github.com/cardano-foundation/CIPs/pull/857
Deprecated & Resubmitted:
- OLD https://github.com/cardano-foundation/CIPs/pull/780
- NEW https://github.com/cardano-foundation/CIPs/pull/862
Abandoned:
- https://github.com/cardano-foundation/CIPs/pull/269
- https://github.com/cardano-foundation/CIPs/pull/276
- https://github.com/cardano-foundation/CIPs/pull/314
- https://github.com/cardano-foundation/CIPs/pull/440
=> Update top-level README: post meeting #93

README.md
Promotions:
- https://github.com/cardano-foundation/CIPs/pull/873
=> Update top-level README: post meeting #94

CIP-0013/README.md
Updated Acceptance Criteria with current state of wallet support
---
([rendered update](https://github.com/MadOrkestra/CIPs/blob/master/CIP-0013/README.md#path-to-active))
=> CIP-0013 | Acceptance Criteria: add more implementations

CIP-0059/feature-table.md
[Rendered](https://github.com/amesgen/CIPs/blob/chang/CIP-0059/feature-table.md)
=> CIP-0059 | Add Chang HF to Features table

CIP-0119/examples/drep.jsonld
=> CIP-0119 | Update drep.jsonld (misspelled `hashAlgorithm`)

CIP-0069/README.md, CIP-0110/README.md, CIP-0117/README.md, CIP-0381/README.md, CIP-1694/README.md, README.md
- Update various CIP statuses in preparation for the Chang upgrade
- Will keep as a draft until hardfork
=> Preparations for Chang upgrade

CIP-1694/README.fr.md
- Correction to the French version related to PR #854
=> CIP-1694 | French - Preparations for Chang upgrade

CIP-0100/README.md
Added 'community tools' entries for cardano-signer and cardano-governance-metadata-rust-lib
=> CIP-0100 | Add 'Community Tooling'  to README.md

CIP-0108/README.md
Added 'community tools' entries for cardano-signer, spo-scripts and cardano-governance-metadata-rust-lib
=> CIP-0108 | Add 'Community Tooling' to README.md

CIP-0054/README.md
CIP54 now has a large toolchain including a reference implementation, example NFT collection, integrated development environment, and blockchain explorer.
https://github.com/kieransimkin/libcip54
https://github.com/kieransimkin/SmartNFTPortal
https://clg.wtf/policy/smart-life
https://nft-playground.dev/
=> CIP-0054 | Add reference implementation

CIP-0119/README.md
- adding rationale for the somewhat confusing `doNotList` property
=> CIP-0119 | Add rationale and context for `doNotList`

README.md
Merged:
- https://github.com/cardano-foundation/CIPs/pull/876
=> Update top-level README: post meeting 99

CIP-1694/README.fr.md
- Correction to the French version related to PR #916
=> CIP-1694 | French - SPO pre-defined voting options

README.md
Merges:
- https://github.com/cardano-foundation/CIPs/pull/857
- https://github.com/cardano-foundation/CIPs/pull/915
=> Update top-level README: post meeting 100

README.md
Merges:
- https://github.com/cardano-foundation/CIPs/pull/796
- https://github.com/cardano-foundation/CIPs/pull/878
- https://github.com/cardano-foundation/CIPs/pull/922
=> Update top-level README: post meeting 103

README.md
Merges:
- https://github.com/cardano-foundation/CIPs/pull/947
=> Update top-level README: post meeting 105

CIP-0122/README.md, CIP-0123/README.md, CIP-0127/README.md, CIP-1694/README.md, README.md
Transitioned CIPs to `active` status
- CIP-122
- CIP-123
- CIP-127
Have i missed any?
=> Update CIP Statuses to reflect changes from Plomin hardfork

CIP-1694/README.fr.md
- Correction to the French version related to PR #985
=> CIP-1694 | French - Update CIP Statuses to reflect changes from Plomin hardfork 

README.md
Coming late because this process slipped my mind after the meeting... noticed when reviewing #993.  Merges:
- https://github.com/cardano-foundation/CIPs/pull/872
- https://github.com/cardano-foundation/CIPs/pull/925
=> Update top-level README: post meeting 106

CIP-0143/README.md, README.md
Merged:
- https://github.com/cardano-foundation/CIPs/pull/944
Also fixes some references from the merged proposal to CPS-0003 that weren't flagged in the review process.
=> Update top-level README: post meeting 108 + CIP-0143 references

CIP-0052/README.md
Hi team, we've been providing auditing services on Cardano for over three years, supporting a wide variety of projects through comprehensive code analysis and tokenomics assessments. Here is a list of projects we've audited. We'd appreciate it if you could add CertiK to the auditors' list in CIP52. Thank you!
Carli3: https://skynet.certik.com/projects/charli3
WingRiders: https://skynet.certik.com/projects/wingriders
Minswap: https://skynet.certik.com/projects/minswap
ChainPort: https://skynet.certik.com/projects/chainport
Multichain: https://skynet.certik.com/projects/multichain
Ikigai Technologies: https://skynet.certik.com/projects/ikigai-technologies
Astarter: https://skynet.certik.com/projects/astarter
iagon: https://skynet.certik.com/projects/iagon
BabySNEK: …
=> CIP-0052 | Add CertiK to the auditors list

README.md
Merges:
* https://github.com/cardano-foundation/CIPs/pull/466
=> Update top-level README: post meeting 109

CIP-0008/README.md
- fix broken link to mesh SDK implementation
- fix one typo: implemtation -> implementation
=> CIP-0008 | fix mesh implementor link and fix one typo

CIP-0089/README.md
@fallen-icarus this looks like a routinely incomplete copy & paste that escaped all our attention.  Noticed when merging #1015 & then browsing through the CIP as if I were a visitor seeing it for the first time.
=> CIP-0089 | Fix repo links: options & aftermarket

README.md
Merges:
* https://github.com/cardano-foundation/CIPs/pull/993
* https://github.com/cardano-foundation/CIPs/pull/999
* https://github.com/cardano-foundation/CIPs/pull/1009
=> Update top-level README: post meeting 110

.github/CIP-TEMPLATE.md, .github/CPS-TEMPLATE.md
Attempts to partly address #1017
- added note to comments of template to nudge authors to self report AI/LLM application within their proposals
=> add note to CIP/CPS templates a optional disclaimer for AI/LLM application

CIP-0100/README.md
- Changed status to `Active`
- Added checkboxes to `Acceptance Criteria`
- Added references to tooling via `Acceptance Criteria`
- Added explicit example to `Best Practices`
=> CIP-100 | update CIP status and add clarification to best practices

README.md
Merges:
- https://github.com/cardano-foundation/CIPs/pull/991
FYI @colll78 today courtesy of @Ryun1 we also caught & fixed an unresolved issue from that PR discussion:
- https://github.com/cardano-foundation/CIPs/pull/1035
=> Update top-level README: post meeting 111

README.md
Merges:
* https://github.com/cardano-foundation/CIPs/pull/767
=>  Update top-level README: post meeting 113

README.md
Merges:
* https://github.com/cardano-foundation/CIPs/pull/1050
=> Update top-level README: post meeting 116

README.md
Merges for originally scheduled meeting (postponed 2 weeks due to Rare Evo):
* https://github.com/cardano-foundation/CIPs/pull/972
* https://github.com/cardano-foundation/CIPs/pull/1033
=> Update top-level README: "ghost" meeting 117
