cardano-foundation/CIPs

CIP5/README.md

CIP5 - Common Bech32 Prefixes

---

CIP-JonathanKnowles-CoinSelectionAlgorithms/CIP-JonathanKnowles-CoinSelectionAlgorithms.md
CIP2/CIP2.md

This PR adds a new _informational_ CIP entitled "**Coin Selection Algorithms for Cardano**".
The purpose of this CIP is to describe, in _human-readable_ terms, the coin selection algorithms currently used by [Cardano Wallet](https://github.com/input-output-hk/cardano-wallet) and other parts of the Cardano ecosystem.
Since the draft is written in Markdown format, see [here](https://github.com/jonathanknowles/CIPs/blob/CIP-JonathanKnowles-CoinSelectionAlgorithms/CIP2/CIP2.md) to read the fully-rendered version.
The draft CIP document is divided into a number of sections:
* Introduces the fundamental concepts behind coin selection.
* Provides a discussion of why coin selection is a non-trivial problem.
* Describes the goals of coin selection algorithms.
* Describes the common interface …

CIP2 - Coin Selection Algorithms

---

CIP2/CIP2.md

This brings CIP 2 into compliance with the header format specified in CIP 1.

Change "Author" to "Authors" in CIP 2.

---

CIP5/LICENSE
CIP5/README.md

- Added a LICENSE file
- Make stake address keys prefixes consistent with address key prefixes

CIP5 updates

---

CIP5/README.md

- For consistency with the rest of the document, replace the term "secret" with "signing" in the `addr_xsk` Bech32 prefix semantic description.
- Strip trailing whitespace throughout the document.

Replace "secret" with "signing" and strip trailing whitespace in CIP5

---

CIP-ShawnMcMurdo-CurvePledgeBenefit/CIP-ShawnMcMurdo-CurvePledgeBenefit.md
CIP-ShawnMcMurdo-CurvePledgeBenefit/rewards.php

Here is my initial CIP for modifying the reward equation to use a curved pledge benefit factor.
Let me know if I did anything wrong oryou have any feedback on the CIP itself or it's contents.
Thanks!

CIP-ShawnMcMurdo-CurvePledgeBenefit

---

CIP2/CIP2.md

Issue #19 
This PR fixes several broken links to reference implementations of coin selection algorithms in CIP-2.
Rather than linking to GitHub pages, we instead link to [Hackage](https://hackage.haskell.org/), which will always serve content that corresponds to the latest version of the `cardano-coin-selection` package, provided that the package is not removed.

[CIP-2] Fix links to reference implementations of coin selection algorithms.

---

CIP5/README.md

Verification key hashes are commonly utilized throughout the Cardano
eco-system. For example, they're used in stake pool registration and
retirement certificates, stake key registration, delegation, and
deregistration certificates, etc. As a result, it seems useful to have a
human-readable prefix by which one can discern the different kinds of
verification key hashes.

Introduce verification key hashes to the CIP5 specification

---

CIP4/CIP4.md

Discussion: https://forum.cardano.org/t/cip4-wallet-checksum/32819
This describes the wallet checksum that is implemented in the Yoroi Extension (and that will eventually be present in Yoroi Mobile). The goal of this CIP is to agree on the generation strategy for standardization with Daedalus in the future.

CIP4 - Wallet checksum

---

CIP10/README.md

This is another one of those cases where I'm pre-emptively reserving the CIP number `10` for this because we need to get this merged regardless and other standards already being written depend on this standard, so it's easier if people can just start referring to CIP10 now.
Cardano transaction metadata forces metadata entries to namespace their content using an unsigned integer key. This specification is a registry of which use cases has allocated which number to avoid collisions.

CIP10 - Transaction Metadata label registry

---

CIP10/README.md

Opening a request to reserve https://nut.link/ metadata oracles metadata labels into CIP10. This is just a toy for now, but might be really used in the future.

CIP10: adding nut.link oracles labels

---

CIP-0013/CIP-0013.md
PaymentUrls/PaymentUrls.md

This is a specification of what we've already implemented in both the Yoroi Extension and in Yoroi Mobile

Cardano URI Scheme

---

CIP-1853/CIP-1853.md

Creating this PR to have a wider discussion and standardize how should the stake pool cold keys be deterministically derived, to e.g. allow their management on hardware wallets
Not sure if right now there are other, possibly not yet published, CIPs that are meant to have this number as a follow-up of CIP-1852, but if they don't introduce a new derivation path purpose, it IMHO makes sense to have 1853 for this CIP which does so

CIP-1853 - HD Stake Pool Cold Keys

---

CIP-0005/CIP-0005.md

Hereby, we propose the prefixes for:
- script hash itself
- verification key hashes that are used inside the script
- signing key corresponding to verification key  used in the script

CIP-5: script prefixes extension

---

CIP-0014/CIP-0014.md

This specification defines a user-facing asset fingerprint as a bech32-encoded blake2b-160 digest of the concatenation of the policy id and the asset name.
The Mary era of Cardano introduces the support for native assets. On the blockchain, native assets are uniquely identified by both their so-called policy id and asset name. Neither the policy id nor the asset name are intended to be human-readable data. 
On the one hand, the policy id is a hash digest of either a monetary script or a Plutus script. On the other hand, the asset name is an arbitrary bytestring of up to 32 bytes (which does not necessarily decode to a valid UTF-8 sequence). In addition, it is possible for an asset to have an empty asset name, or, for assets to have identical asset names under different policies. 
Because …

CIP-0014: User-facing Asset Fingerprint

---

CIP-0003/Icarus.md

Motivation: Document the reason why Trezor's keys/addresses deviate for 24-word mnemonics

CIP-0003 clarify Trezor deviation at 24-word mnemonics

---

CIP-0015/CIP-0015.md

Extends #75. Replaces `slot_number` with `nonce` since we cannot know in advance what slot a transaction will be included into.

Cardano registration metadata changes and signature specification pt.2

---

CIP-0019/CIP-0019-byron-addresses.cddl
CIP-0019/CIP-0019-cardano-addresses.abnf
CIP-0019/CIP-0019.md
README.md

This specification describes the binary structure of addresses in Cardano, covering both addresses introduced in the Shelley era and the legacy format from the Byron era.
Document design choices for posterity. Most applications interacting with the Cardano blockchain will likely not have any need for this level of details, however, some might. This CIP is meant to capture this knowledge. 
In Cardano, addresses are comprised of two parts, a **header** and a **payload**. Depending on the header, the interpretation of the payload varies. 
In the header, bits [7;4] indicate the type of addresses being used; we'll call these four bits the **header type**. The remaining four bits [3;0] are either unused or refer to what we'll call the **network tag**. There are currently 11 types of addresses …

CIP-0019: Cardano Addresses

---

CIP-0005/CIP-0005.md
CIP-1852/CIP-1852.md
CIP-1854/CIP-1854.md
README.md

This document describes how to realize multi-parties transactions in Cardano. It is defined as an alternative to [CIP-1852] for Cardano HD wallets. This specification does not cover the transport and sharing of partially signed transactions which is / will be covered in another document.
Term     | Definition
---      | ---
HD       | Hierarchical Deterministic, refers to wallets as described in [BIP-0032].
Multisig | Shorthand for Multi-party signature scheme. 
Multisig wallets are Cardano wallets capable of providing and tracking keys involved in multi-parties transactions. Such transactions are used to move funds from addresses where (typically) more than one user must sign transactions for its funds to be spent. A simple analogue is a joint bank account where two account holders must …

CIP-1854: Multi-signatures HD Wallets

---

README.md
scripts/build.js
scripts/update-toc.sh

The links in `README.md` were bothering me a little because they show the folder instead of the document.
This changes the link format and adds a script to regenerate the list based on the latest CIP metadata.
The "last updated date" is also changed to YYYY-MM-DD so that nobody gets confused.
I also tested it out with the static site (`npm run build`), and it seems to be an improvement. I also did some minor reformatting to make the front page display better.
* Link to [rendered form](https://github.com/rvl/CIPs/blob/update-toc-script/README.md)

Script to update CIPs list in README.md

---

CIP-1855/CIP-1855.md

See https://github.com/input-output-hk/CIPs/blob/cip-forge-derivation-path/CIP-1855/CIP-1855.md

CIP-1855: add derivation path standard for forging tokens

---

CIP-1852/CIP-1852.md

Before it was still using `chain`, even tho in the diagram of derivation and in the rest of the document it says `role`
So replaced it with `role` as well.

[CIP-1852] Fixed term usage `role` instead of `chain` for consistency

---

CIP-1855/CIP-1855.md

I noticed that the `policy_ix` range was "hardened twice", which it probably shouldn't be.

CIP-1855: fix policy index range

---

CIP-0010/registry.json

Hi Cardano Foundation
we would like to reserve a few entries in the CIP10 registry. These are necessary metadata to allow our milkomeda.com protocol to work with Cardano blockchain.
```json
{
"transaction_metadatum_label": 87,
"description": "milkomeda.com - The protocol magic for the milkomeda protocol"
},
{
"transaction_metadatum_label": 88,
"description": "milkomeda.com - the destination address in the sidechain"
}
```

reserve entries in the metadata mapping for mikomeda protocol

---

CIP-0014/CIP-0014.md

Probably a lot of people looking at this CIP want a JS implementation for their dApp so it's probably best to include the link in the CIP

Add CIP14-js as a reference implementation

---

CIP-0002/README.md
CIP-0003/README.md
CIP-0005/README.md
README.md

Also, fixed a dead-link in CIP-0002 and changed the comment URI (pointing to nothing) to github issues, for lack of a better alternative.

Turn CIP-0002, CIP-0003 & CIP-0005 into 'active'

---

scripts/build.js

Current builds are failing due to CIP-0030 not having specified an email for the author. 
```
3:33:47 AM: > node ./scripts/build.js
3:33:48 AM: /opt/build/repo/scripts/build.js:25
3:33:48 AM:     if (link.match(/^[^@]+@[^@]+$/)) {
3:33:48 AM:              ^
3:33:48 AM: TypeError: Cannot read property 'match' of undefined
3:33:48 AM:     at Authors.split.map.author (/opt/build/repo/scripts/build.js:25:14)
3:33:48 AM:     at Array.map (<anonymous>)
3:33:48 AM:     at Object.<anonymous> (/opt/build/repo/scripts/build.js:22:29)
3:33:48 AM:     at Object.wrapper (/opt/build/repo/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
3:33:48 AM:     at eval (eval at createFunctionContext (/opt/build/repo/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler. …
```

Fix CI build for authors without email.

---

CIP-0019/README.md

This Pull Request makes several changes to CIP-0019 in the hope of improving readability.
The content of the CIP is essentially unchanged, except that implementations are now encouraged to enforce the convention of Shelley → Bech32 and Byron → Base58. This may or may not necessity extra approval.

Improve readability of CIP-0019

---

CIP-0006/README.md
CIP-0006/schema.json
scripts/build.js

This overrides the previous schema and gives priority to the newest version that is in the README. It corresponds to the schema of the latest commit from the PR #15 (https://github.com/cardano-foundation/CIPs/pull/15/commits/4006d061dd3ffdacb77002e3255b745bed17464d)
Fixes #142.

[CIP-0006]: Resolve discrepancy between schema.json and README

---

CIP-0019/CIP-0019-cardano-addresses.abnf
CIP-0019/README.md

- First of all, the wording "output index" was a bit awkward regarding
pointer address. The third component really refers to the position
of the delegation certificate being pointed at. So 'certificate
index' feels like a much better wording.
- Second, the address were typed from 00 to 10 following an
incremental index, but, while it matched the value of the first 4
bits for the types 0 to 7, it was a bit meaningless / confusing for
types 8, 9, 10 which should really be labelled types 14, 15 and 8
for clarity.

CIP-0019 [MINOR] - Some corrections

---

CIP-0005/README.md
CIP-1855/README.md

Complement policy signing keys convention (CIP-1855) with human readable prefix-convention (CIP-0005).

imp CIP-1855: complement with CIP-0005 prefixes

---

CIP-0003/Ledger_BitBox02.md
CIP-0003/README.md

The BitBox02 is compatible with Ledger's derivation of the ED25519-BIP32 root key.

CIP 3: add BitBox02 to the table of derivation methods

---

CIP-0033/README.md

This CIP proposes adding "reference scripts" which allow satisfying script witnessing requirements using scripts attached to outputs rather than scripts provided by the spending transaction.

CIP-33: Reference scripts

---

CIP-0027/README.md

- This CIP is clearly Informational as defined by CIP-0001
- Adoption of this CIP by marketplaces and CNFT issuers is already significant, and CIP Status should be changed to Active[1]
[1] https://twitter.com/Orbital_Lexicon/status/1476336540221595652

CIP27: Change CIP Type and Status

---

CIP-0026/README.md
CIP-0026/schema.json

In the wild and on other chains, tickers get as long as 9 characters.
Of relevance to me, SUNDAE is 6 characters, but CoinMarketCap recognizes
a MILKSHAKE token with 9 characters.
See https://ethereum.stackexchange.com/questions/25619/is-there-length-limits-on-token-symbols
for real world data.
Also relevant: https://github.com/input-output-hk/offchain-metadata-tools/pull/45

Update schema/readme with new ticker max length

---

CIP-0032/README.md

This CIP proposes adding "inline datums" which allow attaching a datum itself rather than a datum hash to an output.

CIP-32: Inline datums

---

CIP-0030/README.md

The current specification of signData() suffers from several issues:
1) There is no way to get the verification keys to verify the signature
returned without prior knowledge
2) The specification did not completely say what would be returned, if
it was merely hex-encoded bytes of the signature or what.
3) The COSE_Sign1/COSE_Sign object would need to be constructed
identically on both the wallet and dApp side which was not covered by
the spec
This update should address these as for 1) the COSE_Sign1 object returned is specified to contain in the `kid` header the verification key. 2) is resolved as well as we no longer have untyped bytes, and 3) is also resolved by nature of explicitly returning it.
The endpoint as a result is simpler and does not cover more complex
CIP-0008/COSE situations …

CIP-0030: update to api.signData()

---

CIP-0005/README.md

We're suggesting the additions mainly for HW wallets.
For "Output datum hash" we also considered using `output_data`.
For "Script data hash" we also considered using `script_data` or `redeemers` (the plural rather than singular).
The `datum` and `redeemer` prefixes were actually proposed to us by @KtorZ, with the reasoning that this naming was used from the start in regard to the eUTXO model.

CIP-0005 | Add prefixes for output datum hash and script data hash

---

CIP-0010/registry.json

Proof of Existence (PoE) claims are something at which blockchains can excel, and  a dedicated metadata label would be a natural addition to this registry.
Certain digital assets, such as NFTs already carry a measure of existence proof via the combination of 721-format metadata and basic transaction timestamp.
For other digital assets PoE claim options seem to be less formalized. And while the 674 metadata message label could be used for Proof of Existence claims,  such embedding could also prove semantically confusing.
A dedicated label would also allow for more flexibility in the record format (note: this proposal is just for the label, and not for any particular record format).
I propose using the label "309" as it is short, otherwise unallocated and (trivially) resembles the mirror …

Add Proof of Existence record label to registry.json

---

CIP-0030/README.md

Currently CIP30 defines the `getUtxos` endpoint should return `undefined` if the requested amount can't be satisfied
The problem is that browser message passing uses JSON and `undefined` is not valid JSON. This can easily introduce subtle bugs (some libraries silently convert `undefined` to `null`) and it's needless complexity when we could just define the spec to return null instead.
Strictly speaking this is a breaking change, but I'm not sure if it will affect app at the moment.
Another option would be to return an error instead of null which I think also makes sense

CIP30: getUtxos null instead of undefined

---

CIP-0033/README.md

This matches the recent changes to CIP-31 and 32.
See https://github.com/cardano-foundation/CIPs/pull/161#issuecomment-1030181440.

CIP-0033 | update to ban reference scripts in the presence of old scripts

---

CIP-0036/README.md
CIP-0042/README.md

This CIP proposes to add a new builtin for serialising `BuiltinData` to `BuiltinByteString`
[Rendered Github](https://github.com/ch1bo/CIPs/blob/ch1bo/new-plutus-builtin-serialiseBuiltinData/CIP-0036/README.md)
[Rendered Netlify](https://deploy-preview-218--cips.netlify.app/cips/cip36/)

CIP-0042 | New plutus builtin: serialiseBuiltinData

---

CIP-0010/registry.json

Greetings Cardano Foundation team,
The team at [paradiso.app](https://paradiso.app) would like to reserve our transaction metadatum entries in the CIP-0010 registry.
We are using the entries below for storing our onchain metadata.
```
{
"transaction_metadatum_label": 1188,
"description": "paradiso.app marketplace metadata"
},
{
"transaction_metadatum_label": 1189,
"description": "paradiso.app services metadata"
}
```

[paradiso.app] reserve transaction metadatum labels

---

CIP-0055/README.md
CIP-coinsPerUTxOByte/README.md

This informational CIP extends CIP-0028 to introduce a change to one of the Alonzo protocol parameters in the Babbage era, namely `lovelacePerUTxOWord`. We propose to have this updateable parameter be based on bytes instead of words (eight bytes).

CIP-0055? | Babbage Era Protocol Parameters

---

README.md

This fixes something accidentally left out of https://github.com/cardano-foundation/CIPs/pull/216#issuecomment-1172955353 without the 18 month commit history as seen in https://github.com/cardano-foundation/CIPs/pull/285 and https://github.com/cardano-foundation/CIPs/pull/286 (due to a problem in my own fork).

fix CIP-0040 table omissions

---

CIP-0059/README.md
CIP-namesSurroundingFeatures/README.md
CIP-namesSurroundingFeatures/feature-table.md

This informational CIP seeks to clarify the language around groups of features. At the very least, it provides some history.

CIP-0059? | Terminology Surrounding Core Features

---

CIP-0055/README.md

CIP-55 was an information CIP regarding the Babbage era protocol parameters. In it, it was explained how the new parameter
`coinsPerUTxOByte` is used. The explanation contained a mistake, namely not accounting for the constant overhead.
Thank you @gitmachtl for pointing this out! https://github.com/cardano-foundation/CIPs/pull/265#issuecomment-1179338845

CIP-0055 correction: constant overhead in babbageMinUTxOValue

---

CIP-0010/registry.json

We intend to register a new transaction metadatum label `1870` which identifies [Open Badges v2.0](https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html) compliant metadata.
Open Badges is an open standard originally developed by the Mozilla Foundation and now maintained by [IMS Global](https://www.imsglobal.org/activity/digital-badges) to represent verifiable achievements (e.g. educational certificates or certificates from instructional lectures).
_Open Badges are information-rich visual tokens of verifiable achievements earned by recipients and easily shared on the web and via social media. The Open Badges standard describes a method for packaging information about accomplishments, embedding it into portable image files as digital badges, and includes resources for …

Register new CIP-10 metadatum label for Open Badges v2.0 compliant transaction metadata

---

README.md

Some things have gone out of date on the top-level `README` mostly due to the migration from Crowdcast to Discord:
- The link to the meeting forum itself has changed.
- Since this document was written, meetings are transcribed as well as summarised.
- We aren't making the recordings of the Discord meetings available yet (right?) so there's nothing to link to under "recorded".
- Some minor cleanup: grammar and the index character 🛈 before the blockquote: which sometimes renders as "info" (i-in-a-circle) but shows up as tofu on my own system so isn't universally valid.
Please let me know if we should still include the Crowdcast link because of the old meeting recordings.  I've not included it because there was talk in one of our last process meetings about dropping the Crowdcast …

updates to CIP meeting links and text since Discord migration

---

CIP-0055/README.md

This fixes a mistake in CIP-55.
The minimum lovelace calculation for the Babbage era was missing needed parenthesis. Credit goes to @lehins for catching this!

missing parenthesis in Babbage min utxo calc

---

CIP-0021/README.md

This PR updates CIP-0021 with Babbage changes. The exact release date of the updated Ledger app is not yet clear but it should be within a month. Trezor update should be released on August 17.
[Babbage CDDL](https://github.com/input-output-hk/cardano-ledger/blob/master/eras/babbage/test-suite/cddl-files/babbage.cddl)

CIP-0021 | Add Babbage changes

---

CIP-0011/README.md
CIP-0035/README.md

As identified in [#109](https://github.com/cardano-foundation/CIPs/issues/109#issuecomment-1193054082) the relative links between CIPs which work on GitHub are broken on `cips.cardano.org`. Pending some site remediation,  all CIPs referring to content of a different CIP must use absolute links.  The links changed here are the ones identified in https://github.com/cardano-foundation/CIPs/issues/109#issuecomment-1193400948.

absolute paths for remaining cross-CIP relative links

---

CIP-0037/README.md
cip-caseygibson-dynamicsaturation.md

This CIP is a proposal to correlate a SPOs total pledge to the pools saturation level. This takes the importance of the pledge and pool saturation away from the pool entity and places it on the SPO entity. This is to patch the loophole that single entity SPOs have exploited in running pool farms with significant amounts of stake. 
The intention of the pool saturation was to limit how dominant a single entity could become, however they have bypassed this intention by creating secondary pools.
This proposal will mean that a SPO will have a saturation point across all their pools based on how much pledge they have across them.

CIP-0037? | Dynamic Saturation based on Pledge

---

CIP-0010/registry.json

Added transaction_metadatum_label 1888 to registry.json for the Amphitheatre by The APE Society compliant metadata.

update registry.json: ape society amphitheatre

---

CIP-0060/README.md
CIP-0060/cddl/version-1.cddl
README.md

The music community on Cardano is still working on this actively, but I wanted to get this placeholder PR up to hopefully grab the CIP-60 number.

CIP-0060? | Music Token Metadata

---

CIP-0010/registry.json

Signed-off-by: Miguel Angel Cabrera Minagorri <devgorri@gmail.com>
Update `registry.json` to add a metadata key to route Shareslake's bridge transactions.
We will introduce an object as the value of the key containing the destination/origin network and the destination address / original network Tx.

Update registry.json - Shareslake bridge metadata key

---

CIP-0059/feature-table.md

Based on the block here:
https://cexplorer.io/block/eea1247726ababb0b15ef7068b6917ceb6ebe3021c40fe44608585bba44e24b6
Amusingly, the first block in the babbage era has `babb` as a substring :)

CIP-0059 | Add dates and slot numbers to the table

---

README.md

The CIP-0005 information doesn't reflect the correct status. It's supposed to be `Active` as mentioned in #145. I assume the revert back to `Draft` is done by accident in #164 as there isn't any discussion regarding the CIP-0005. The mistake occurred in the [Current CIPs Status Table](https://github.com/danivideda/CIPs/blob/67fb3222f93e6603bf761d5148eb6e3447302c4a/BiweeklyMeetings/2021-11-23.md#current-cips-in-the-cip-repository-and-their-status) section within the `BiweeklyMeetings/2021-11-23.md` file.

Top-Level README | Fix CIP-0005 status

---

CIP-0036/schema.cddl

Removed the notion of "proportion" from the schema replacing it with the term "weight" since "weight" is used within the specification. cc: @kevinhammond

CIP-0036 | Changed terminology in schema to match README specification

---

CIP-0026/README.md

This small change proposal makes so that there can be competing claims about a subject's property. Prevents hijacking of a property's by simply allowing the first value. Also for the metadata server client to decide (based on annotated signature), which claim it trust

CIP-0026 | subject properties return multiple claims

---

CIP-0068/README.md

`decimals` in metadata don't need to be `big_int`, but can be `int` also. @KtorZ pointed that out before for the`version` field, but I have overseen it for `decimals`.
I also realized it makes little sense to follow the same constraints of the cardano-token-registry for `logo`, which only allows you to use PNGs as bytestrings. Here the image is in the datum and potentially in an inline datum. Having only the option to store the image as bytestring on-chain wouldn't be ideal. A `URI` is much better suited here, which gives more flexibility and allows you to use also other image types e.g. `.jpg`
@rphair

CIP-0068: Small change in 333 FT sub standard 

---

CIP-0010/registry.json

Add metadatum labels for cardanohosts.com tokens. These tokens will be used for hosting websites on the Cardano blockchain.

CIP-0010 | Add cardanohosts.com metadatum labels

---

CIP-0071/README.md
CIP-0071/example/voting.html
CIP-0071/example/voting.js

This is the initial commit for a proposed Cardano Improvement Proposal (CIP) that would enable NFT projects that did not want to use a governance or other native fungible asset to perform verifiable on-chain votes.
[ Documentation: README.md, example/ ]
---
[see rendered Markdown](https://github.com/thaddeusdiamond/CIPs/blob/cip-71/CIP-0071/README.md)

CIP-0071? | Non-Fungible Token (NFT) Proxy Voting Standard

---

CIP-0001/README.md
CIP-0013/README.md
README.md

Aside from general reformatting as per https://github.com/cardano-foundation/CIPs/issues/389:
- Standard CIP sections were H1s and other subheadings were too deep.
- There is no section "Read More" (which was a bare list of related URLs) in the standard format so I've embedded those links inline. @SebastienGllmt @v-almonacid feel free to suggest any corrections to this for the links you've chosen.

CIP-0013 | Adjust preamble and structure w.r.t CIP-0001

---

CIP-0034/registry.json

Some applications may still want to refer to the legacy testnet even though it's not running anymore for things like error messages or migrating old configs, but this was made difficult by https://github.com/cardano-foundation/CIPs/pull/332 removing the legacy testnet from the registry.
I propose we keep it there, and just rename it to "legacy testnet"
----
Additionally, I noticed the networkIDs specified for the new testnets were incorrect. You can see in the Cardano codebase that [creating an address](https://github.com/input-output-hk/cardano-node/blob/f4dc7c4a8f21f4912903ad71a7ad485225141e20/cardano-api/src/Cardano/Api/Address.hs#L301) calls [toShelleyNetwork](https://github.com/input-output-hk/cardano-node/blob/853a5607bf8ee3d7e0d0859f910081a8fe0d0a9f/cardano-api/src/Cardano/Api/Netwo …

CIP-0034 | Include legacy testnet

---

CIP-0010/registry.json

Requesting removal of paradiso.app metadatum labels.
We are shutting down this month, and would like to free these labels up.
Original PR which reserved these labels is listed below for reference:
https://github.com/cardano-foundation/CIPs/pull/272

[paradiso.app] remove transaction metadatum labels

---

CIP-0001/README.md

Have been jumping around between these sections a lot, so fixed the links that didn't match the anchors (`status` vs. `statuses`) and a quick reference to Categories.  Also checked that all the other page outline links are working.

CIP-0001 | Fix status anchors, add Categories link

---

CIP-0005/README.md
CIP-0036/README.md

- Concerns were raised around the definition of CIP-36's voting keys and how these should be represented in supporting tooling (good spot from @janmazak and @gitmachtl). 
- Avoid confusion with current and future protocol governance.
CIP-05
- [825d54d](https://github.com/cardano-foundation/CIPs/pull/427/commits/825d54da6487fa84eb398604df335928881f4d19): Added `cvote_sk` and `cvote_vk` prefixes to be used when Bech32 encoding CIP-36's voting keys. As per [gitmachtl's suggestion](https://github.com/cardano-foundation/CIPs/pull/427#issuecomment-1383960821).
CIP-36 
- Added clarity for voting / vote key terminology. Linking to CIP-05 prefixes.
- Gave examples of potential naming supporting tooling could use.
- [4f6b879](https://github.com/cardano-foundation/CIPs/pull/427/commits/4f6b8794e51ce1 …

CIP-0005, CIP-0036 | Added clarity to voting key definitions

---

CIP-0052/README.md

Added field for public key information for auditors. This to be used to verify signed audit certification metadata.

CIP-0052 | Add public keys to auditor table

---

CIP-0035/README.md

- Include discussion of Plutus Core language versions and how they change.
- Use "ledger language" instead of "language version" or "ledger language version" to avoid confusion
- Remove the reference to the 'Draft' status.
- Minor prose improvements.
The actual Plutus Core language version was not discussed previously, as it hadn't really seen much use. However we might want to change Plutus Core itself in the medium-term future, so we should make it clear how to do that.
I also tried to clear up some confusing language - the use of 'language version' for the ledger languages was just too confusing, especially in the presence of _another_ language version! So I've opted to just refer to 'ledger languages', which I think is clearer.
I'm planning to do another PR to do more adjustments to …

CIP-0035 | Redraft to handle Plutus Core language versions

---

CIP-0049/README.md
CIP-0074/README.md
scripts/build.js
templates/cips.hbs

Fixes #436 
- :round_pushpin: **Fix editors parsing + provide better debugging on malformed input data.**
- :round_pushpin: **Display CIPs by category, if it exists.**
This also sorts categories such that 'All' is always first and 'Unclassified' is always last.

Fix website build

---

CIP-0031/README.md
CIP-0032/README.md
CIP-0033/README.md
CIP-0035/README.md

This updates CIP-35 to be in line with the new CIP-1.
The main changes are:
- Remove some sections that are IMO implied by CIP-1, e.g. the necessity of a clear implementation plan.
- Delete the CIP registry, since you can just list the category
- Explicitly identify the 'Plutus' category and list the reviewers. At the moment it's just me, maybe it should be more people?
- Attempt to clarify the prose a bit.
There's one very questionable thing that I've done, which is to assert that CIPs in the crossover between the Ledger and Plutus should be in both categories. I just went ahead and wrote that here, but I defer to the resolution of https://github.com/cardano-foundation/CIPs/issues/433 and I'll change this depending on what gets decided there.

CIP-0035 | Update for new CIP-1

---

CIP-0001/README.md

Fixes issues identified in https://github.com/cardano-foundation/CIPs/issues/439 based on last 2 months or so of common problems with submitted CIP PR's: mainly to save manual triage & editing work and repeated requests from editors to authors.
There is some deliberate redundancy here in _Path to Active_ instructions, mainly because this is the most often omitted section of submitted CIPs.  Because authors have been overlooking it in the  _Status: Proposed_ section, its requirement for all but `Inactive` proposals is repeated in a few different contexts to catch readers wherever they land.
([updated CIP-0001 in this PR branch](https://github.com/rphair/CIPs/blob/cip-0001-section-headings-etc/CIP-0001/README.md))

CIP-0001 | Section headers, Path to active, PR submission

---

CIP-0001/README.md

Thanks @KtorZ for merging https://github.com/cardano-foundation/CIPs/pull/450 so quickly, but I didn't notice till now that although I'd linked the new _Path to Active_ section inline I hadn't added it to the Table of Contents.

CIP-0001 | add Path to Active to Table of Contents

---

CIP-0036/schema.cddl

Changes #427 introduced proposed that tool makers supporting this CIP should call the keys described within it "(CIP-36) vote keys" over "voting keys". This change was reflected in the specification and testvectors file, but not accurately reflected in the CDDL schema.
Rename `voting_pub_key` to be `cip36_vote_pub_key` in the CDDL schema file.
This change matches the CDDL schema to naming suggested within the CIP specification itself.
**Note**: Thank you @janmazak for spotting this.

CIP-0036 | Fix CDDL naming to match changes in spec from #427 

---

CIP-0001/README.md
README.md

Dear all,
I would be grateful for you to consider me as a CIP editor candidate.
For the last six months I have been keenly engaged with the CIP process . Notably across this time I have primarily worked on engaging and acting on feedback for CIPs adjacent to Project Catalyst. See some contributions: [#373](https://github.com/cardano-foundation/CIPs/pull/373), [#426](https://github.com/cardano-foundation/CIPs/pull/426), [#427](https://github.com/cardano-foundation/CIPs/pull/427), [#461](https://github.com/cardano-foundation/CIPs/pull/461), throughout [#296](https://github.com/cardano-foundation/CIPs/pull/296#issuecomment-1354745558). Further, I have been keen to spread awareness of the CIP process and its progress, in this light writing and sharing weekly CIP updates ([What happened in …

CIP Editor Application | Ryan Williams (@Ryun1)

---

CIP-0068/README.md

By reading the CIP-0068 and trying to implement it myself I was convinced the asset name should literally be prefixed with the label `(100)` and not with the implementation suggested by CIP-0067, there was no reference whatsoever to the correct label convention as far as I am aware and this PR tries to make things more clear for future developers attempting to implement CIP-0068 on their own.

CIP-0068 | Clarify label prefixes

---

CIP-0030/README.md
README.md

This has been a recurring topic regarding extensions of CIP-0030.
Given that this CIP is effectively active (hence the status change in
this commit), we can't simply keep modifying it because it then
becomes hard for DApps to keep track of what is supported by wallet
providers and what isn't.
In this commit, I henceforth propose an extension scheme based off
CIPs. Wallet providers are expected to support the base API given by
CIP-0030 and new extensions or modifications of that API can be
brought in through extension CIPs. Upon initialization, Dapps can
interrogate the wallet about what CIPs extensions it supports and
process or fail accordingly based on whether the wallet provides the
desired functionality.

CIP-0030 | Upgrade to latest format & propose version / extension scheme

---

CIP-0080/README.md
CIP-tx-serialization-deprecation-cycles/README.md
README.md

This CIP proposes a policy for how we manage the backwards compatibility of the binary format for transactions. The summary is:
* We should strive to maintain backwards compatibility (which we've maintained since the Shelley phase began).
* Serious flaws can be fixed immediately (at the next hard fork), and can break backwards compatibility.
* Non-Serious flaws can be fixed (at the next hard fork), but the old format must be supported for at least six months with support ending at the next hard fork event after the six months have passed.
---
([current draft in branch](https://github.com/JaredCorduan/CIPs/tree/jc/tx-serialization/CIP-tx-serialization-deprecation-cycles))

CIP-0080? | Transaction Serialization Deprecation Cycle

---

CIP-0001/README.md
README.md

@crptmppt hasn't been active for more than a year; which is a requirement for being an editor. We need to know we can rely on people for meetings and driving the CIP process. 
Thanks for kickstarting the CIP process and the work done; it's been crucial to the success of the CIP process. Feel free to re-apply if and once your focus becomes once again Cardano.

Remove Frederic Johnson from CIP editors

---

CIP-0001/README.md
CIP-0075/README.md
CIP-0082/README.md

I believe that this better reflects the latest discussions on the topic. But that is up-to-debate. We could keep the more specific "RSS" category and simply mark all CIPs directed towards this category as "Inactive"; this would ease their finding later on although there aren't so many "Ledger" CIPs either. 
It just has been bothering me that this category exists, is clearly targeted at some specific areas of the ledger, yet is not embracing the CIP process. Unlike other pre-registered categories that tend to have multi-tenant ownership (e.g. wallets).

Remove RSS category, use Ledger for CIP-0075 & CIP-0082

---

CIP-0006/README.md
CIP-0025/README.md
CIP-0059/README.md
CIP-0074/README.md
CIP-1854/README.md
CIP-1855/README.md

Fixes https://github.com/cardano-foundation/CIPs/issues/485.  Readers and authors on CIP repository and Developer Portal reported links from CIPs to reference papers were out of date due to `hydra.iohk.io` being superseded.
@Ryun1 identified https://github.com/input-output-hk/cardano-ledger/commit/7bb099326546f910539b75e835b07322fdf88bc5 which has been helpful in narrowing down the target documents at their new locations.  Before we merge this I hope we can get approval or correction from the CIP authors and representative paper authors that the new link targets are appropriate:
cc @gufmar @alessandrokonrad @SmaugPool @JaredCorduan @ADARobinHood @KtorZ @disassembler @dcoutts @WhatisRT
CIPs affected (see reference issue for details):
- CIP-0006
- CIP-0025
- CIP-0059
- CIP-0074
- CIP-1854
- …

Fix broken links from CIPs to hydra.iohk.io

---

CIP-0067/registry.json
CIP-0068/README.md

Rich-fungible tokens sit somewhere between FTs and NFTs. They need the richness of metadata provided by CIP-25, but require decimals like FTs.
One example is a fractionalized NFT.  It could be represented by 100 tokens and setting decimals to 2 to show that there was only 1 NFT.
Alternatively, you could choose to mint 100m tokens and set decimals to 6. In this scenario, holding 1 token would represent holding 1% as there are 100 tokens in circulation.
A final example would be a card-style game where you have a number of the player cards as NFTs `(222)`, but interchangeable mana/land/utility cards would be semi-fungible tokens `(444)`
---
([updated CIP-0068 rendered in branch](https://github.com/AndrewWestberg/CIPs/blob/amw/cip68_semi_fungible/CIP-0068/README.md))

CIP-0068 | Add RFT Rich-fungible token support

---

CIP-0035/README.md

As it says. We need to be able to do this in order to (de)serialize
scripts.

CIP-0035 | Require proposals for new builtin types to explain how they will be (de)serialized

---

CIP-0057/README.md
CIP-0057/schemas/README.md
CIP-0057/schemas/plutus-blueprint-argument.json
CIP-0057/schemas/plutus-blueprint-parameter.json
CIP-0057/schemas/plutus-blueprint.json
CIP-0057/schemas/plutus-builtin.json
CIP-0057/schemas/plutus-data.json
README.md

This proposal specifies a language for documenting Plutus contracts in a machine-readable manner. This is akin to what [OpenAPI](https://swagger.io/specification) or [AsyncAPI](https://www.asyncapi.com/docs/specifications/v2.4.0) are for, documenting HTTP services and asynchronous services respectively. In a similar fashion, A Plutus contract has a binary interface which is mostly defined by its datum and redeemer. Since all interactions with contracts are done through transactions, we can also model _endpoints_ of a contract as transitions from a known state to another purely declaratively. 
This document is therefore a meta-specification defining the vocabulary and validation rules with which one can specify a Plutus contract interface, a.k.a **Plutus contract blueprint**.
---
[see …

CIP-0057? | Plutus Smart-Contract Blueprints

---

README.md

Agreed to promote at least meeting & confirmed on Discord last week:
- https://github.com/cardano-foundation/CIPs/pull/442
- https://github.com/cardano-foundation/CIPs/pull/499
Plus there were some others who'd not made it onto `README.md` after being promoted, so I went over the list & added these anything that had been updated in the PR alone.  Merges in the meantime were all for updates & corrections if I remember correctly; I'll check again now & feel free to double-check.
I have removed the 2 deprecated proposals.  Another idea would be to add a "deprecated" section but I would prefer not to because
1. the deprecations are already listed via a GitHub tag, so we can find them easily.
2. I would prefer focusing interest from third parties' attention on the "waiting for authors" …

Update top-level README for meeting #66 and meantime CIP promotions

---

CIP-0010/registry.json

This is a reduced version of https://github.com/cardano-foundation/CIPs/pull/511 that only adds the tag to the registry.

CIP-0010 | Add Agora proposal creation metadata to registry

---

CIP-0069/README.md

The aim of the CIP is to allow more secure designs, streamline the developer experience and increase the design space of Cardano validators. 
All three purposes are achieved by removing the `Datum` out of a spending script's signature, to be the exact same as every other type of script. Datum is made available in `ScriptPurpose` instead. 
This change lets us use one script as both a spending and a minting validator, meaning that we resolve a well known protocol design problem of 'mutually dependent' validators, where a minting validator needs as parameter a spending validator, and the spending validator needs as parameter the minting one. 
With this CIP, they can be merged into a single script, enabling us to enable the two-way (or more) dependency where necessary. 
---
[see rendered …

CIP-0069? | Plutus Script Type Uniformization

---

CIP-0086/README.md

Places where CIP web content is built, particularly the Developer Portal, can use different defaults as the root of relative pathnames.  Therefore links to local asset files must begin with `./` which we generally have for CIPs & only notice when e.g. the build process for the Dev Portal generates a warning and then links to an incorrect URL:
```
Exhaustive list of all broken links found:
- On source page path = /docs/governance/cardano-improvement-proposals/CIP-0086:
-> linking to cddl/version_1.cddl (resolved as: /docs/governance/cardano-improvement-proposals/cddl/version_1.cddl)
-> linking to cddl/version_2.cddl (resolved as: /docs/governance/cardano-improvement-proposals/cddl/version_2.cddl)
```
For now I guess editors should just keep aware of this during the review process, along …

CIP-0086 | Fix relative links to asset files

---

CPS-0005/README.md
CPS-????/README.md

This CPS pulls together motivation from a number of CIPs, with the aim of describing a nubmer of issues in once place, rather than having them repeated amongst the many CIPs addressing various aspects of the problem.
---
[rendered proposal in branch](https://github.com/michaelpj/CIPs/blob/mpj/script-interaction-cps/CPS-%3F%3F%3F%3F/README.md)

CPS-0005 | Plutus Script Usability

---

README.md

In the merge conflict resulting from an old code base for https://github.com/cardano-foundation/CIPs/pull/380, this tip (for the meaning of the "status" field) appeared under the CIP table _or_ the CPS table depending on the source branch.
To avoid creating an incorrect top level README upon merging #380, in fixing that merge conflict I positioned the "tip" correctly...  but (to avoid introducing a content change irrelevant to CIP-1694) I didn't correct the tip for CPS statuses, which are different from CIP statuses.  That fix is done here.
Likewise @KtorZ @Ryun1 we will have to please review and merge this ASAP otherwise the same thing will keep happening for other CIP merges which might update the README file.  At the very least it should be merged before the customary "chore" of …

Fix status links in top level README

---

.github/CIP-TEMPLATE.md
.github/CPS-TEMPLATE.md
CIP-0075/README.md
CIP-0082/README.md
README.md

As previously arranged in https://github.com/cardano-foundation/CIPs/pull/456#issuecomment-1579110371, RSS proposals can all be given a status of `Proposed` and category of `Ledger` now that CIP-0084 is merged with a language clarification both extending & limiting the Ledger team's responsibility for these CIPs (quoted in https://github.com/cardano-foundation/CIPs/pull/456#issuecomment-1585558784).
More recent CIPs written according to the updated CIP-0001 (0075, 0082: cc @TobiasFancee) have their `Inactive` status removed and no longer have a strike-out on the CIP table.  (re: https://github.com/cardano-foundation/CIPs/pull/482)
Older CIPs also now have status `Proposed` in the top level table, and will soon be updated for compatibility with CIP-0001 with headers fixed to use the new …

Top README: update for CIP-0084 consequences to RSS proposals

---

CIP-0060/README.md

The Developer Portal build of the CIP directory structure depends on relative links being prefixed by `./` so this is a routine fix that comes up from time to time (we are gradually getting to all of these).
Not sure why these problems aren't all exposed at once, but local builds of the Dev Poral generate warnings like these for relative pathnames and often expand the absolute URL wrong (cc @katomm):
```
[WARNING] Docusaurus found broken links!
Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
Exhaustive list of all broken links found:
- On source page path = …
```

CIP-0060 | Fix relative links

---

CIP-0007/README.md

Fixes https://github.com/cardano-foundation/CIPs/issues/532.
@KtorZ please check the _Path to Active_ is OK here is OK before I might also apply the same Acceptance Criteria in https://github.com/cardano-foundation/CIPs/issues/533 & https://github.com/cardano-foundation/CIPs/issues/535.

CIP-0007 | Adjust preamble and structure w.r.t CIP-0001

---

CIP-0001/README.md

([new addition](https://github.com/cardano-foundation/CIPs/blob/i18n/CIP-0001/README.md#translations) = Translations section)

Extend CIP-0001 to cover internationalized content

---

CIP-1694/README.md

Ledger GitHub repo [cardano-ledger](https://github.com/input-output-hk/cardano-ledger) was released while CIP-1694 was evolving; this corrects obsolete hydra based URLs as we have for https://github.com/cardano-foundation/CIPs/pull/487.
Not submitted with contemporary PR https://github.com/cardano-foundation/CIPs/pull/547 because the other one might require some consideration, while this is definitely a straightforward change that can be done immediately.
cc @WhatisRT

CIP-1694 correction | Fix ledger spec links

---

CIP-1694/README.fr.md

- Change old hydra ledger spec links to GitHub repo (#548)  (Commit baa4ad5) 
- Removed rationale TOC link "Treasury withdrawals vs Project Catalyst" (#547) (Commit 89bb166)

CIP-1694 | Update French version to Commit (89bb166)

---

CIP-0381/README.md

The cardano base branch has been merged, and the PR for plutus bindings is open input-output-hk/plutus#5231. Some of the initial notation has changed. This PR adapts the CIP to the new notation.

CIP-0381 | Adapt to Plutus bindings

---

README.md

One thing to keep in mind: the content of draft CIP-3 (now removed as closed at author's own request, and therefore I marked "likely deprecated" because the drafted approach was more specific than a general "programmed token behaviour" CPS would have to be) will probably keep being revisited somehow, so:
- Currently we're losing the link https://github.com/cardano-foundation/CIPs/pull/382 to this material (maybe to regain someday if & when this `README` is every automatically generated, or built from PR labels & linked to a label listing) but for now we will have to remember, in any future revivals of the "smart token" idea, to ask if they want to continue @szist's work.

Update top-level README: last 2 weeks' activity

---

CIP-0019/README.md

I believe the intent here was to define the terms used above - however the wrong term was used. PaymentKeyHash vs PubKeyHash

CIP-0019 Update | Small naming fix

---

CIP-0025/README.md

As discussed in https://github.com/cardano-foundation/CIPs/pull/392#issuecomment-1612564049 there is a flaw in the design of CIP 25 should new token minting policies make burning permissionless.
In particular, the CIP mentions the latest minting transaction of a token to be the most up-to-date version of the metadata of a token. Burning tokens is not explicitly excluded from being a minting transaction (where technically both minting and burning are minting operations for the ledger, just with positive/negative amounts). If burning would become permisionless, users can arbitrarily change the metadata of their tokens. Hence this change proposes to explicitly forbid burning transactions to be counted for CIP 25 updates.

CIP-0025 | Restrict to minting (positive amounts)

---

README.md

- Assigns CIP numbers 98 through 100 for 3 proposals confirmed as candidates in editors' meeting today.
- Deprecates CPS-2 by request of author in https://github.com/cardano-foundation/CIPs/pull/374#issuecomment-1646581391.
- Merges CIP50. 🥳

Update top-level README: meeting 70 period

---

CIP-0068/README.md

1. This patch tries to improve 222, 333 & 444 media types and URIs descriptions.
2. It also proposes to remove the optional top level `mediaType` in 222 & 444 for the following reasons:
* because it is optional, it cannot be relied on and is therefore basically useless at best
* it has actually been counterproductive in CIP 25 as some users have minted NFTs with `video/...` or `model/...` media (mime) type for `image` URI, ignoring the `image/*` constraint (I will propose to remove it too in CIP25 if this is accepted here)
3. It adds the Arweave scheme (`ar://`) in the list of supported URI schemes. I wonder though if the CIP should have such a hard list of supported schemes or just suggestions?
4. It improves the References section and uses links instead of text
PS: Not sure how to avoid …

CIP-0068 | Improve image types and URI descriptions

---

CIP-0030/README.md

See these few small formatting fixes.
1. Changed _old style_ links that pointed to `CIP-0005.md`, these would require a short redirect because of past change to CIP markdown file naming.
2. Added javascript language indicators for code snippet data types and error codes.
3. Added missing `APIError` for `api.getExtensions()`.
4. Fixed incorrect reference to `cardano.{walletName}.extensions` which was removed during development of #446. Replaced with correct reference to `api.getExtensions()`.
5. Fixed highlighting for references to `APIError`, to all be `APIError` and not APIError.
6. A couple small spelling fixes.
1. Just more convenient to follow direct links.
2. Will rendered the snippets with syntax highlighting which improves readability.
3. This seems like an oversight and not …

CIP-0030 | A few small fixes

---

CIP-0050/README.md

Usual problem: not having any screening process or script to find the relative links not prefixed by `./`, we will currently run full speed ahead into this when the merged CIP is built on the Developer Portal (see below; cc @katomm @fill-the-fill @rdlrt).
@KtorZ if you have ideas about how to deal with this proactively maybe we can work together to automate the checks somehow.  This is one case where the right approach to scripting could save a lot of manual work by editors. 🤔
---
```
Error: ENOENT: no such file or directory, open './static/img/cip/./CIP-0050/images/k-effective.png'
... path: './static/img/cip/./CIP-0050/images/k-effective.png'
}
```

CIP-0050 | Fix relative links

---

CIP-0093/README.md

The same old thing, generally to fix builds of derived sites especially the Cardano Developer Portal (warnings generated below).  Hard to spot these in GitHub review, where relative paths between CIPs are valid.  Someday our site builders might correct for this, but for newcomers to this issue we resolved in the meantime to make all the cross-CIP URLs absolute.  cc @jmagan @katomm
---
```
[WARNING] Docs markdown link couldn't be resolved: (/CIP-0008/README.md) in "/home/rphair/archive/build/developer-portal/docs/governance/cardano-improvement-proposals/CIP-0093.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (/CIP-0030/README.md) in "/home/rphair/archive/build/developer-portal/docs/governance/cardano-improvement-proposals/CIP-0093.md" for version current …
```

CIP-0093 | Update cross-CIP links to anchored relative paths

---

CIP-0001/README.md

Motivation and method already discussed at CIP meeting with characteristic example still pending merge in https://github.com/cardano-foundation/CIPs/pull/582.
One side effect of this PR: original language said to use a 8-10 digit commit hash, while the GitHub histories contain only 7-digit commit hashes.  As already identified in https://github.com/cardano-foundation/CIPs/pull/539#pullrequestreview-1514656299, searches for longer hashes on the GitHub history page will fail if longer hashes are used, making the hashes more difficult in general to verify.

CIP-0001 | Allow ISO date if translation source uncommitted

---

CIP-0054/README.md

`\<` is supported by GitHub to escape HTML but not part of Markdown spec and not supported by showdown, breaking CIP-0054 rendering on https://cips.cardano.org/:
By escaping instead the opening angle bracket with `&lt;`, both GitHub and showdown rendering work correctly:
GitHub rendering:
https://github.com/SmaugPool/CIPs/tree/cip54-fix-rendering/CIP-0054
FYI: @kieransimkin

CIP-0054 | Fix API headers for markdown portability

---

CIP-1694/README.md

This PR makes the final semantic changes that we currently intend to make. The main addition is the proposal policy, and some changes to restore internal consistency. We've also added a Changelog at the bottom that documents these and past changes. This supersedes #545. These are the changes:
- Add support for a proposal policy
- All governance actions are now enacted one epoch after they have been ratified. This is necessary to comply with requirements coming from moving the stake distribution to disk.
- Fix some places where past design changes were not applied fully
- Move the DRep restrictions in the optional section, and add a few new optional ideas
- Rename protocol parameters for consistency
- Smaller changes & clarifications
- Add Changelog

CIP-1694 | Design changes after the Edinburgh workshop

---

CIP-0030/README.md

- Encourage that extension endpoints are explicitly namespaced by their cip/extension name.
example: `api.cip95.getPubDRepKey()`
I believe this is a sensible change to make ahead of the emergence of CIP-30 extensions, such as https://github.com/cardano-foundation/CIPs/pull/509.
- This prevents extensions from creating conflicting endpoints with the same naming.
- This should help simplify wallet implementations, by allowing easier routing of requests.
- This should simplify extension management for dApps.
---
Thanks @stevenj and @refi93 for the suggestion.

CIP-0030 | Encourage namespaced extension endpoints

---

CIP-1694/README.fr.md

Traduction a partir de la révision: https://github.com/cardano-foundation/CIPs/commit/e35beddb575b1a55fbf2cc327df94b076447f0b6
Ce PR apporte les derniers changements sémantiques que les auteurs du CIP-1694 ont actuellement l'intention d'apporter. Le principal ajout concerne la politique de proposition, ainsi que quelques modifications visant à restaurer la cohérence interne. Il y a également l'ajout d'un journal des modifications en bas qui documente ces modifications et les modifications passées. Ceci remplace le #545. Voici les changements :
* Ajout de la prise en charge d'une politique de proposition
* Toutes les actions de gouvernance sont désormais adoptées une époque après avoir été ratifiées. Ceci est nécessaire pour se conformer aux exigences liées au déplacement de la …

CIP-1694 | French - Design changes after the Edinburgh workshop

---

CIP-0001/README.md

Discussion begun in https://github.com/cardano-foundation/CIPs/issues/590 and currently, as agreed in today's editor meeting, with consensus so far that:
- the "pipe" (`|`) is a better choice than the colon to avoid YAML errors
- this may also be applicable to other CIP names: e.g. may be helpful for new token types as per CIP-0068, so should be generalised into CIP-0001... as opposed to CIP-0030 which would only cover extensions to the web-wallet bridge.
On that last note we also suggested @Ryun1 might add a similar instruction to CIP-0030 that those extensions be named as such (with `Web-Wallet Bridge |`), once it's confirmed here.  In anticipation of this I've added an H6 (so far unused) to the document so it can be referenced easily with an external link.
BTW the merged CIP-0095 …

CIP-0001 | Titles for CIPs with common purpose

---

CIP-0010/registry.json
CIP-0025/README.md
README.md

As we have standardized the use of fungible tokens for media/collectible tokens (ie: art editions & book copies), we need to avoid using "NFT" as a blanket term in CIP documentation as it can create confusion around whether a CIP includes these other token variants.

CIP-0025 | Change "NFT" to "token"

---

CIP-0015/README.md

Rewrite to update CIP-0015 to match latest CIP-0001 structure, see [Issue #389](https://github.com/cardano-foundation/CIPs/issues/389).
I chose to go with a category of `Metadata` rather than `Catalyst`, as `Catalyst` is yet to officially registered as a category.
cc: @stevenj

CIP-0015 | Adjust preamble and structure w.r.t CIP-0001

---

CIP-0030/README.md

Recognised in https://github.com/cardano-foundation/CIPs/pull/591#issuecomment-1712917686 (cc @SmaugPool) and cleaned up here since running this code through Showdown in site builders causes text inside angle brackets beginning `\<` to be dropped unless quoted literally in Markdown (as code would be).
To avoid too many unnecessary changes, I've only applied this change to the [API section](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0030#initial-api) and not the preceding error types or data types.  Perhaps for functional & aesthetic considerations other reviewers might think these literals should also be quoted as code. 🤔 cc @rooooooooob
- NOTE data type `cbor<T>` suffers the same problem I've also quoted it as code.
- @Ryun1 @Crypto2099 @SebastienGllmt please look at the …

CIP-0030 | Fix API headers for markdown portability

---

CIP-0102/README.md
CPS-0007/README.md
README.md

Promotes:
- https://github.com/cardano-foundation/CIPs/pull/551
Deprecates:
- https://github.com/cardano-foundation/CIPs/pull/530#issuecomment-1769653477
and also fixes some white space inconsistencies from commits by editors in final editing round today (p.s. + further housekeeping below).

Update top-level README: post meeting #75

---

CIP-0057/README.md

- Blueprint generation and loading is supported in OpShin as of https://github.com/OpShin/opshin/pull/279
- Blueprint leveraging is underway in pycardano as of https://github.com/Python-Cardano/pycardano/pull/276 ff
Note: ImperatorLang is the deprecated name of OpShin.

CIP-0057 | Update Implementation Status

---

CIP-0010/registry.json

We would like to register a new metadata label `1904` reserved for proof of origin and quality control in the supply chain space. The first use case is our [pilot project](https://cardanofoundation.org/en/news/cardano-foundation-partners-with-georgian-national-wine-agency/) at the Cardano Foundation with the National Wine Agency of Georgia.
We have prepared a specification which should hopefully become its own CIP but is still internally under final review. We would like to for now reserve this label and later update the description to point to the CIP.
The standard aims to cover proof of origin (see some initial documentation on the metadata [here](https://cardano-foundation.github.io/cf-georgian-wine-resolver/)) and quality control through Certificates of Conformity (documentation …

CIP-0010 | Add proof of origin metadata label

---

CIP-0035/README.md

Fixes #691.
@michaelpj this was mostly done in https://github.com/cardano-foundation/CIPs/pull/437: I just added the history and set `Implementors: NA` in imitation of CIP-0084.  If there's a better choice for `Implementors` please say so.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0035/CIP-0035/README.md))

CIP-0035 | Adjust preamble and structure w.r.t CIP-0001

---

CIP-0017/README.md

Fixes #661.
([edited proposal](https://github.com/rphair/CIPs/blob/remediate-0017/CIP-0017/README.md))

CIP-0017 | Adjust preamble and structure w.r.t CIP-0001

---

CIP-0036/README.md
README.md

Fixes #604.
- Removed `Voltaire` from the title as it is now clear that this will not be used for Voltaire.
- Moved rationale to `Rationale` section.
- Moved `Changelog` subsection to `Rationale` section.
- Added `Path to Active` section.
- Added links/missing words/missing grammar.
- Removed extra spaces and unused reference.
------
[Rendered Updated Proposal](https://github.com/Ryun1/CIPs/blob/remediate-36/CIP-0036/README.md)

CIP-0036 | Adjust preamble and structure w.r.t CIP-0001

---

CIP-0027/README.md

Fixes #673.
@Crypto2099 as with other "remediations" of ubiquitously implemented proposals for #389 I've set `Implementors` (at least initially) to `NA` since there's no complete list that would not overrun the header.  If you can think of a subset of implementors that makes sense in this context & conveys something useful, please feel free to suggest it here.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0027/CIP-0027/README.md))

CIP-0027 | Adjust preamble and structure w.r.t CIP-0001

---

CIP-0105/README.md

- Changed the description of DRep keys to not use abbreviation
- This matches how cardano-cli describes the keys
Thanks for the spot @gitmachtl

CIP-0105 | Remove abbreviations from DRep key tooling descriptions

---

CIP-0009/README.md

Fixes #649.
([edited version](https://github.com/rphair/CIPs/blob/remediate-0009/CIP-0009/README.md))

CIP-0009 | Adjust preamble and structure w.r.t CIP-0001

---

.github/CIP-TEMPLATE.md
CIP-0010/README.md

Fixes https://github.com/cardano-foundation/CIPs/issues/651.
**NOTE** this says `Implementors: NA` simply because "everybody" (the interested parties referred to in _Path to Active_) implements it.... and because an intelligent reading of this CIP will suggest a list of implementing providers in the `registry.json` file itself.
([edited version](https://github.com/rphair/CIPs/blob/remediate-0010/CIP-0010/README.md))

CIP-0010 | Adjust preamble and structure w.r.t CIP-0001

---

CIP-0016/README.md

Fixes #659.
([edited proposal](https://github.com/rphair/CIPs/blob/remediate-0016/CIP-0016/README.md))

CIP-0016 | Adjust preamble and structure w.r.t CIP-0001

---

CIP-0037/README.md

Fixes #693.
I don't think this proposal really got much editorial attention prior to merging, and the attitude about RSS proposals (prior to the ruling by default that they would be `Inactive`) was "Why not merge it without a rigorous review... since declaring it `Active` would depend on a bureaucratic process which still remains undefined."
So somehow it missed our across-the-board standardisation of RSS proposals, which I've applied here including a `Ledger` category and the same `Path to Active` boilerplate I wrote & applied to the other RSS CIPs.
@CyberCyclone I had to haul what you'd written as _Path to Active_ and some other non-canonical sections into the _Motivation_ section since that is really the only place for inspirational writing about why we might need the CIP.
... This …

CIP-0037 | Adjust preamble and structure w.r.t CIP-0001

---

CIP-0052/README.md

Fixes #701.
@simonjohnthompson I've had to make some adjustments due to more rigorous formatting requirements and stricter requirements in anticipation of becoming `Active` since this was originally merged.
The main text shuffle was to move your _Appendix_ into the "Prerequisites" for your _Specification_.  This assumes these terms are essential to implementing the audit process exactly as envisioned in your Specification.
* If that assumption isn't true, or if the background material is cumbersome in that position, especially if common knowledge to auditors, this might be offloaded to a document like "Handbook for audits" that exists outside the CIP.
I had to delete the "example audit" since its web page is defunct and the Wayback Machine version doesn't run the right code to download …

CIP-0052 | Adjust preamble and structure w.r.t CIP-0001

---

CIP-0055/README.md

Fixes #706.
@JaredCorduan I hope history will forgive me for not changing "era" to "ledger era" everywhere in this document as per the nearly concurrent CIP-0059... though I have used it in this new "Path to Active" (if that mismatch is a problem to anyone's reading please say so).
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0055/CIP-0055/README.md))

CIP-0055 | Adjust preamble and structure w.r.t CIP-0001

---

CIP-0059/README.md

Fixes #708.
License discrepancy between CC in the header and Apache in the footer... I've ruled in favour of Creative Commons licensing here because there's no code in here to justify Apache licensing.
Had to introduce some newlines in the markdown to break up some of the longer paragraphs that were barriers to readability.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0059/CIP-0059/README.md))

CIP-0059 | Adjust preamble and structure w.r.t CIP-0001

---

CIP-0068/README.md

Fixes  #714.
@Crypto2099 had already done some good work to remediate this with respect to CIP-0001 in #586 but it was still left with non-standard major headings undefined in CIP-0001 (like `## References`) and the _Path to Active_ needed some items shuttled between Acceptance and Implementation.
In cases like this I would want to put References in the section where it is most applicable.  Usually that's the Specification which draws upon standards documented elsewhere, but sometimes that's Rationale because these references can be either reference implementations or points of contrast with approaches others have taken.  
In any case I would be open to discussion about where things get moved but for sake of parseability I think we need to stick to the half dozen major sections defined in …

CIP-0068 | Adjust preamble and structure w.r.t CIP-0001

---

CIP-0028/README.md

Fixes #675.
@kevinhammond as with https://github.com/cardano-foundation/CIPs/pull/650 I've resolved the discrepancy in licensing agreements in favour of Apache (CC was indicated in the YAML header).
Editors: we need to keep an eye on how these Protocol Parameter CIPs are stacking on top of each other.  The last solid resolution I remember (before @Ryun1 @Crypto2099 arrived) was that protocol parameter CIPs would describe differences with the previous ledger era, rather than a complete re-enumeration of parameters... but a lot of this material feels already stated in CIP-0009.
So although solving any issues of reference & redundancy is beyond the scope of the #389 "Remediation" (and therefore doesn't have to be attended to in this PR) I still think we should keep an eye on this issue (with …

CIP-0028 | Adjust preamble and structure w.r.t CIP-0001

---

CIP-0040/README.md
README.md

Fixes #695.
@SebastienGllmt @WhatisRT there was a title clash between a longer title in the CIP vs. a shorter title in the top level `README`.  I've ruled in favour of the longer title since I think it captures the point of the CIP better... but if that would cause any confusion we'll set them both to the shorter one.
([updated proposal](https://github.com/rphair/CIPs/blob/remediate-0040/CIP-0040/README.md))

CIP-0040 | Adjust preamble and structure w.r.t CIP-0001

---

CIP-0005/README.md
CIP-0105/README.md

…and CC members
Committee members and DReps can be identified by a credential that can be either an Ed25519 verification key OR  a Script. The current prefixes do not make any distinction between these. It is good for clarity and transparency to make a clear distinction between the two types.

CIP-0005 | Distinguish between key based and script based conway credentials

---

CIP-1694/README.md

The stake distribution used for talllying spo votes is not the _registered voting stake_ (delegated to DReps), but instead the _active stake_: the stake delegated and active on the epoch for block production.

CIP-1694 | Correctly characterise delegated active stake

---

CIP-1694/README.fr.md

- Correction to the french version related to PR #745 
- From commit "fix errata about stake distribution."

 CIP-1694 | French - Correctly characterise delegated active stake

---

CIP-0100/README.md
CIP-0100/cip-0100.common.jsonld
CIP-0100/cip-0100.common.schema.json
CIP-0100/example.body.canonical
CIP-0100/example.canonical
CIP-0100/example.json

Whilst making some[ more example files](https://github.com/Ryun1/metadata), I have found a couple inconsistencies with the provided examples.
- Removed proposal property which does not exist in the standard
- Aligned capitalisation
- Changed hashing algorithm from blake2b-224 to blake2b-256 as only 256 [is the only supported](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0100/README.md?plain=1#L108)
- Changed links to reference github rather than CIPs website
cc @Quantumplation

CIP-0100 | Small clean up on example files

---

.github/CPS-TEMPLATE.md
CIP-9999/README.md

To fix:
- the CPS half of https://github.com/cardano-foundation/CIPs/issues/731 (already fixed for CIPs)
- to legitimise the top level `References` section - and maybe other optional sections - as per discussion beginning https://github.com/cardano-foundation/CIPs/pull/638#discussion_r1439333464
- to complete what was started in #730 which added optional sections for the CIP but not for the CPS.
Whatever _optional sections_ we agree on for CPSs should be more reserved than for CIPs which have more of a precent for formality... otherwise the less formal problem statements will have arbitrary top-level sections everywhere for things that would be better focused into the 5 major headings so that CIP authors can more readily use them.
- This is why I left out the "custom" sections which we …

CIP-9999 | Structure and template revisions

---

CIP-0110/README.md
CIP-script-ref-plutus-v1/README.md

Plutus v1 scripts are unable to use the CIP-0031 / CIP-0033 reference inputs / script references to reduce transaction size. As a result, between 80% and 90% of every block is occupied by repeating the same script bytes over and over.
This problem will not go away even as new protocols that do support Plutus v2 are released: these protocols exist forever, and in many cases, will hold hundreds of thousands in liquidity practically forever.  As long as that is the case, they will represent an arbitrage opportunity that someone somewhere will want to take advantage of.
This proposal suggests a very simple (albeit perhaps aesthetically uncouth), backwards compatible way to support script references for Plutus v1 scripts.
[Rendered](https://github.com/Quantumplation/CIPs/blob/pi/plutusv1-script …

CIP-0110? | Plutus v1 compatible script references

---

README.md

New candidates:
- https://github.com/cardano-foundation/CIPs/pull/444
- https://github.com/cardano-foundation/CIPs/pull/752
- https://github.com/cardano-foundation/CIPs/pull/753
- https://github.com/cardano-foundation/CIPs/pull/638
- https://github.com/cardano-foundation/CIPs/pull/751
Merges:
- https://github.com/cardano-foundation/CIPs/pull/619
- https://github.com/cardano-foundation/CIPs/pull/641
- https://github.com/cardano-foundation/CIPs/pull/679

Update top-level README: post meeting #81

---

CIP-????/README.md

Based on some discussions with Pi and others.
Some tasks today are difficult because we don't have the data structures to do them efficiently. This CPS outlines a couple of examples and gestures towards some possible solutions (which will require a proper CIP).
-----------------------------------------
[Rendered Version](https://github.com/michaelpj/CIPs/blob/master/CIP-%3F%3F%3F%3F/README.md)

CPS-0013? | Better builtin data structures in Plutus

---

CIP-0088/README.md
CIP-0100/README.md

This I believe will fix the errors currently appearing when building the Developer Portal (cc @katomm), going on several weeks now since the last updates of CIP-0088 (@Crypto2099) and CIP-0100 (@Ryun1):
```
- On source page path = /docs/governance/cardano-improvement-proposals/CIP-0088:
-> linking to CIPs/0025/CIP25_v1.cddl (resolved as: /docs/governance/cardano-improvement-proposals/CIPs/0025/CIP25_v1.cddl)
-> linking to CIPs/0025 (resolved as: /docs/governance/cardano-improvement-proposals/CIPs/0025)
-> linking to CIPs/0026/CIP26_v1.cddl (resolved as: /docs/governance/cardano-improvement-proposals/CIPs/0026/CIP26_v1.cddl)
-> linking to CIPs/0026 (resolved as: /docs/governance/cardano-improvement-proposals/CIPs/0026)
-> /* a few more in the same pattern */
- On source page path = …
```

CIP-0088, CIP-0100 | Fix relative pathnames

---

CIP-0057/schemas/plutus-builtin.json
CIP-0057/schemas/plutus-data.json

This PR fixes a subtle mistake in the JSON schema that is caught by the popular JSON schema validator `ajv`:
```
Error: strict mode: missing type "object" for keyword "required" at "https://cips.cardano.org/cips/cip57/schemas/plutus-builtin.json#" (strictTypes)
at checkStrictMode (/home/yura/projects/cardano/plutus/node_modules/ajv/dist/compile/util.js:174:15)
at strictTypesError (/home/yura/projects/cardano/plutus/node_modules/ajv/dist/compile/validate/index.js:286:32)
at checkKeywordTypes (/home/yura/projects/cardano/plutus/node_modules/ajv/dist/compile/validate/index.js:262:17)
at checkStrictTypes (/home/yura/projects/cardano/plutus/node_modules/ajv/dist/compile/validate/index.js:234:5)
at schemaKeywords (/home/yura/projects/cardano/plutus/node_modules/ajv/dist/compile/validate/index.js …
```

CIP-0057 | Fix schema validation error (strict mode)

---

CIP-0057/schemas/plutus-blueprint.json

While the next Plutus Ledger Language version is not yet available on mainnet, its conceivable that one might want to produce a Contract  Blueprint for it. 
This PR adds `v3` to the list of allowed `plutusVersion` values.

CIP-0057 | Include Plutus V3

---

README.md

New candidates:
- https://github.com/cardano-foundation/CIPs/pull/766
~@Crypto2099 @Ryun1 @stevenj - we might also merge these between meetings:~ Merges:
- https://github.com/cardano-foundation/CIPs/pull/751
- https://github.com/cardano-foundation/CIPs/pull/752
- https://github.com/cardano-foundation/CIPs/pull/753
... ~if we~ with post-meeting fix Ryan's requested minor edits, and add Steven's admonition about using tags/keys from the Proposed version of the CIP prior to official assignment by IANA.  ~So if merged before this PR is merged I'll add them here.~

Update top-level README: post meeting #83

---

CIP-0010/registry.json

At Seedtrace (https://seedtrace.org/), we have been working with the Cardano Foundation to set up storage of farmer fair payments data in the metadata of Cardano blockchain transactions. This is already live on the mainnet, and in the future we would like to extend the usage for other traceable data in our client's supply chains.
As suggested by our advisor from the Cardano Foundation, we have chosen a metadata key number which our transactions metadata will use and this PR is for registering this number to Seedtrace.

CIP-0010 | Register metadata key number: 620

---

CPS-0009/README.md

This PR adds a link from [CPS-0009](https://github.com/cardano-foundation/CIPs/tree/master/CPS-0009) to the coin selection algorithm used by `cardano-wallet`.

CPS-0009 | Add link to Cardano Wallet coin selection library

---

CIP-0100/README.md

This follows up https://github.com/cardano-foundation/CIPs/pull/763 for other proposals identified as having lists of names before the CIP's or CPS's terms of documentation & Internet search significance.
@Quantumplation this covers your documents identified [here on Discord](https://discord.com/channels/971785110770831360/992011119872970762/1214918602663272478) (cc @klntsky) if skipping [CPS-0007](https://github.com/cardano-foundation/CIPs/tree/master/CPS-0007#abstract)... which I would recommend because the link to the end section would be nearly as much text as the names currently there.  If any objections (for the sake of consistency) we can update that one as well.
The remaining documents are these from @Ryun1 - one currently open PRs (so can be modified there):
- …

CIP-0100 | Move Acknowledgements into optional section

---

CPS-0005/README.md
CPS-0007/README.md
CPS-0010/README.md
CPS-0011/README.md
CPS-0013/README.md

Implements change agreed in #762 for all merged CPSs.  These all add CC licensing (vs. Apache, so far) since, as mainly will be true for CPSs, they're all narrative & no code.
This is also a check to see if there will be any downstream problems, mainly due to the new mandatory field in the YAML preamble, on (cc @fill-the-fill @katomm):
- `cips.cardano.org` ([cf-cip-frontend](https://github.com/cardano-foundation/cf-cip-frontend))
- the CIP / CPS build script on the Dev Portal
TODO wait before merging to confirm no downstream problems before:

add License field + Copyright section to all CPSs

---

CIP-0083/README.md

**A.** There is one **under-specification** that I found worth adding.
AES-256-CBC cipher as implemented in OpenSSL requires messages that are a multiple of 16-bytes. If the message does not fit then padding is used. In the current PR the padding technique is explicitly exhibited. It is very important information for those that implement this CIP - as I was in the context of cardano-wallet.
**B.** The second thing worth mentioning is the example specified, ie.
```
openssl enc -e -aes-256-cbc -pbkdf2 -iter 10000 -a -k "cardano" <<< '["Invoice-No: 123456789","Order-No: 7654321","Email: john@doe.com"]'
```  
It is unfortunate as `<<<` is adding new line!
```
Perform shell expansion on word and pass the result to standard input. This is known as a here-string. Compare the use of word in …
```

CIP-0083 | confirm openssl behaviour, fix command line example

---

CIP-0104/README.md
CIP-XXXX/README.md

A [CIP-30 extension](https://cips.cardano.org/cips/cip30/#cardanowalletnameenableextensionsextensionpromiseapi) that allows for a DApp (if allowed) to fetch the connected account public key. Utilizes yet to-be-merged CIP-30 namespace PR https://github.com/cardano-foundation/CIPs/pull/577.
---
([rendered proposal in branch](https://github.com/Scitz0/CIPs/blob/cip30-ext-accountpub/CIP-0104/README.md))

CIP-0104? | Web-Wallet Bridge - Account public key

---

cip-observe-script-type/README.md

We propose to introduce a new Plutus scripts type Observe in addition to those currently available (spending, certifying, rewarding, minting, drep). The purpose of this script type is to allow arbitrary validation logic to be decoupled from any ledger action. Since observe validators are decoupled from actions, you can run them in a transaction without needing to perform any associated action (ie you don't need to consume a script input, or mint a token, or withdraw from a staking script just to execute this validator).
---
[Rendered Proposal on Fork](https://github.com/colll78/CIPs/blob/Observe-Script-Type/cip-observe-script-type/README.md)

CIP-0112? | Observe script type

---

CIP-0010/registry.json

Provides a general purpose tag specifically for indexing and other uses off-chain by oracles and oracle consumers.

CIP-0010 | Add oracle tx metadata tag to registry

---

CIP-0068/README.md

In the Cardano node, Plutus Data bytes are limited to 64 bytes. There is an issue where IPFS V2 uris are 66 bytes so they require the use of an NFT.
This is already the case for CIP-25 NFTs so it should also be the case for CIP-68.
This pr adds: / [ * bounded_bytes ] to the uri pattern.

CIP-0068 | Allow [* bounded_bytes] for images

---

CIP-0010/registry.json

Noticed one entry had a typo, decided to fix it.

CIP-0010 | Misspelled keyword for 1694 label

---

CIP-1694/README.md

I was trying to test ratification of info actions, before I was told that info actions can never be ratified or enacted. This change is intended to clarify that point.

CIP-1694 | Reword note on info actions

---

CIP-0069/README.md

Closes #769 
cc @michaelpj @lehins @MicroProofs @rphair @KtorZ @zygomeb @L-as

CIP-0069 | add Datum to ScriptContext

---

CIP-0117/README.md
CIP-????/README.md

There is a papercut in how we check whether scripts accept transactions. There are a few ways that people can make mistakes, not notice, and have their scripts fail open. This proposal suggests that we instead be prescriptive about what scripts must return in order to succeed, which would make such mistakes quickly obvious.
This is not a particularly important change, but it would be relatively cheap to do and would fix a minor problem.
---
[Rendered Proposal on Fork](https://github.com/michaelpj/CIPs/blob/mpj/explicit-fail/CIP-0117/README.md) < edit: changed to latest version in branch

CIP-0117? | Explicit script return values

---

CIP-1694/README.md

- Replace "New Constitutional Committee" governance action by "Update Committee"
- Replace "Update to the Constitution" governance action by "New Constitution". This is how it is called on-chain when submitting this governance action and when querying its tag. I also changed it for semantic reasons. 
- Replace "Proposal policy" by "Guardrails Script". This wording is mainly used broadly by everyone and is also the wording used in the Interim constitution Article VIII, Apendix 1, (Automated Checking ("Guardrails Script")).
- Update each parameters name tags as seen on chain. (conway era)
- Replace "Pre-defined Drep" name by "Pre-defined voting option" at 3 different places in the CIP-1694 (Which already got me in big trouble, but lets not go there. =P)

CIP-1694 | Updates and semantics

---

CIP-0100/example.body.json
CIP-0100/example.body.nq
CIP-0100/example.json
CIP-0100/test-vector.md

Thanks for raising this @disassembler 🤝
- Incorrect capitalisation of the reference type "Other" within the example, [here](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0100/example.json#L51C20-L51C27).
- Fixed capitalisation within example.
- Remade all other downstream files from example.
- Not sure why there was so much change within `example.body.nq`?

CIP-100 | Remake example to fix incorrect capitalisation on references type

---

CIP-0057/README.md
CIP-0057/schemas/plutus-blueprint.json

- :round_pushpin: **Add 'compiler' field to the blueprint.**
This is a purely additive, and optional, change. So it shouldn't pose much problem to add (existing implementation that supports blueprints would keep working). Yet it documents a field that we've started using in Aiken and that has turned to be incredibly useful.
- :round_pushpin: **Document few more projects in connection with blueprints.**

CIP-0057 | Add 'compiler' field

---

CIP-0122/README.md

This fixes some errors (mostly formatting, but some copy-paste issues), as well as some naming errors, in CIP-122.
In the process of implementation of CIP-122 (and CIP-123), the names of the functions to be implemented were changed, and `writeBits` ended up having a change in its signature, which the current versions of both documents don't reflect. I'm guessing that there is more of a process for non-typographical changes: if so, I'm happy to follow it, but decided to send this PR with typographical fixes only for now.

CIP-0122 | Typographical fixes & corrections

---

CPS-0016/README.md
CPS-XXXX/README.md

[Rendered Version](https://github.com/Crypto2099/CIPs/blob/Cardano-URI-CPS/CPS-0016/README.md)
This CPS proposes to be a central repository of information related to CIP-13 `web+cardano:` URIs and the different schemes, authorities, and solutions that exist to help expand and aid in integration.

CPS-0016? | Cardano URIs

---

CONTRIBUTING

This answers suggestion https://github.com/cardano-foundation/CIPs/issues/793#issuecomment-2033983895 from the initial consideration of the new CIPs Wiki (https://github.com/cardano-foundation/CIPs/wiki).
However, it would be a huge duplication of effort to [build & maintain a CONTRIBUTING.md file](https://mozillascience.github.io/working-open-workshop/contributing/) because it's already accessible & up to date in the Wiki itself.  Still, to carry on the tradition of offline access through these top-level files (e.g. `LICENSE`), I've included brief instructions to build an offline copy of the Wiki with `git clone`.
So I believe the file should just be these 2 pieces of information.  In my opinion it's even too much overhead to use Markdown, and as a text file it follows the convention set …

Add top level CONTRIBUTING file

---

CPS-0008/README.md
README.md

Merged:
- https://github.com/cardano-foundation/CIPs/pull/605
- https://github.com/cardano-foundation/CIPs/pull/758
Notes, as per https://github.com/cardano-foundation/CIPs/issues/883#issuecomment-2305540624:
* This doesn't update the dates of the "candidate" tables since they will be replaced with a state query in a forthcoming PR within the hour & I don't want to cause a merge conflict.
* Neither does it add this week's newly assigned CIP number(s)s, since from now on those will be automatically listed by the updated title according to the `State: Confirmed` tag that we apply when promoting at/after the CIP meeting.

Update top-level README: post meeting #95

---

README.md

After consideration in https://github.com/cardano-foundation/CIPs/pull/887#issuecomment-2310470656 — for increased visibility in the community, especially to attract attention from stakeholders & implementors for any affected CIPs.
This uses a low bar for query compared to the _Candidate_ list: only querying the `Update` tag without checking for a review `State:` tag... relying on that one bit of editor confirmation to keep spam or inappropriate update requests from being linked from the front page.
I don't see the harm in including likely "abandoned" or "deprecated" `Update` PR's here... in fact I believe it's important to include them because CIP/CPS updates aren't included in the _Stalled / Waiting For Authors_ list (since the latter is only for new CIPs/CPSs).
---
([newly added …

Add Updates section to top level README

---

README.md

Merges:
- https://github.com/cardano-foundation/CIPs/pull/459
- https://github.com/cardano-foundation/CIPs/pull/488
- https://github.com/cardano-foundation/CIPs/pull/625

Update top-level README: post meeting #96

---

CIP-0095/README.md

Minor wording improvements to the standard committed alongside.

CIP-0095 | Misspelling of `DeprecatedCertificate`

---

CIP-0001/README.md
README.md

Removes @SebastienGllmt as suggested 28 August on the CIP Discord's editor channel — without dispute as yet — after long period of inactivity.
BTW we are due for some CIP-0001 updates and in a soon-coming PR I'm going to suggest we add a small section _Emeritus editors_ as they have [in EIP-1](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1.md#eip-editors), with all (4) past CIP editors listed: since so far there are no retired editors who haven't significantly contributed to the work we have on file today.

Remove inactive editors from CIP editors lists

---

CIP-0001/README.md
README.md

Inadvertently introduced in https://github.com/cardano-foundation/CIPs/pull/901 - not noticing the 2 extra empty cells that stop the Markdown from rendering as a table.

Top-level README, CIP-0001 | Fix table formatting

---

CIP-0001/README.md
README.md

With this PR I would like to put myself forward in the role as a CIP editor. Given this [PR](https://github.com/cardano-foundation/CIPs/pull/901), I would love to fill these big shoes and contribute to the continuation of the CIP process as it is now. 
A big thanks to both @KtorZ and @SebastienGllmt for their effort and, above all, their great technical minds.
Regarding my competence for this role, I have contributed to various CIP's and even co-authored some myself. I hope others recognize this and have faith in my ability to execute this role successfully :smiley:

Add Thomas Vellekoop as a CIP editor

---

CIP-0001/README.md
CIP-9999/README.md
README.md

This has all the CIP-0001 pending updates I've collected, resulting from many review threads since the beginning of the year.  Most of these points have either been explicitly or tacitly agreed upon already but of course the changes need vigorous review: especially change to Enlistment as per https://github.com/cardano-foundation/CIPs/issues/898.
([updated CIP-0001](https://github.com/rphair/CIPs/blob/cip-0001-overhaul%2Bprocess-update/CIP-0001/README.md))
---
changed document title to `CIP Process` 
- To make consistent with [README table](https://github.com/cardano-foundation/CIPs/blob/master/README.md#cardano-improvement-proposals-cip)
- This title makes more sense as title on derived web sites, especially Developer Portal (https://github.com/cardano-foundation/CIPs/issues/900#issuecomm …

CIP-0001 | Annual overhaul and process update

---

CIP-0101/README.md
CIP-0127/README.md

As currently appearing with potential YAML parsing errors here:
- https://github.com/cardano-foundation/CIPs/blob/master/CIP-0101/README.md
- https://github.com/cardano-foundation/CIPs/blob/master/CIP-0127/README.md
and breaking downstream renderers as reported here:
- https://github.com/cardano-foundation/developer-portal/pull/1335#issuecomment-2420391244
I say "potential" because the backtick seems only to be a problem in the first position of the YAML value.  However, for the sake of authors & readers, if we don't allow it in the initial position it would be confusing to allow it anywhere... and irrational to ask authors & editors to rearrange the titles for the backticks only to appear in the middle.

CIP-0101, CIP-0127 | Remove backticks from literals in titles

---

CIP-1694/README.md

Addition of language that allows for SPOs to delegate to pre-defined voting options. PR created by Adam Rusch and Johnny Kelly. Idea for achieving SPO pre-defined voting options came from Martin Lang of ATADA Stake Pool at the September 23, 2024 Ledger Working Group meeting.

CIP-1694 | SPO pre-defined voting options

---

README.md

Now that the "candidates" list is being updated automatically, it's been harder to remember to update times of table modifications manually.
- CIP table is updated to match https://github.com/cardano-foundation/CIPs/pull/928/commits/4ab399f52b861374bcac596e92ada94845d46f9b of https://github.com/cardano-foundation/CIPs/pull/928
- CPS table was correctly updated in https://github.com/cardano-foundation/CIPs/pull/899
One thing I thought of adding: more precise modification times in UTC: now that we have editors working across 12 time zones again.  Why not:
- These changes don't just happen at the meeting, or the last commit in the meeting update PR, but over a period of all the editors approving them: which makes precision irrelevant and perhaps even misleading.
- I think we are looking …

Top README: update modtime from #928

---

CIP-0105/README.md
CIP-0105/test-vectors.md
CIP-0105/test-vectors/test-vector-1.md
CIP-0105/test-vectors/test-vector-2.md
CIP-0105/test-vectors/test-vector-3.md
CIP-0105/test-vectors/test-vector-4.md

In accordance to CIP-0129 missing data in all test vectors was added, mainly for credentials.
Also proper tags ("deprecated") where needed were added. 
After the current PR is merged CIP-0105 will be thoroughly compliant with CIP-0129 from the point of view of test data

CIP-0105 | Add test vectors

---

CIP-0119/README.md
CIP-0119/cip-0119.common.schema.json

This PR addresses the issue https://github.com/cardano-foundation/CIPs/issues/945, by adding an `@` symbol at the beginning of name of the `@type` field of the `references` field of `CIP-0119`, updating it in the JSON schema and the README.md.
Fixes #945.

CIP-0119 | Add "@" to the "@type" field of "references"

---

CIP-0108/examples/no-confidence.jsonld
CIP-0108/test-vector.md

This PR addresses the issue https://github.com/cardano-foundation/CIPs/issues/949, by ensuring `CIP-0008` is used in capital letters in the `witnessAlgorithm` field of the `witness` type in CIP-0108, updating the "no-confidence" example and the test vector Markdown documentation.
Fixes #949.

CIP-0108 | Ensure "CIP-0008" is in capital letters

---

CIP-0005/README.md

- Remove `drep_script`, `cc_cold_script` and `cc_hot_script` from the `Hashes` table
- because these are present within the `Deprecated Governance Prefixes` so I believe its a mistake they are in both tables.
- added header to the the `Deprecated Governance Prefixes` table to fix the rendering
- fix spelling mistakes of constitutional throughout
- replace abbreviations of terms in `Miscellaneous` to make entries more consistent
- add CIP-105 reference to improve navigation of depreciated prefixes

CIP-0005 | Typos and tidy of deprecated governance prefixes

---

CIP-0129/README.md

**Problem**
- The formatting of the governance action id examples made them hard to follow
**Changes**
- Removed abbreviations
- Made capatalizion consistent
- Fixed formatting of examples so not all rendered on one line
- Added 'original id' to examples

CIP-0129 | Improve gov action id description and examples clarity

---

CIP-0010/registry.json

The Transaction Metadata Label to be registered is 21325.
This value 21325 represents the last 16 bits of 344977920845, which is the decimal representation of the concatenation of the hexadecimals 50 52 49 53 4d that form the word PRISM in ASCII.
https://github.com/input-output-hk/prism-did-method-spec

CIP-0010 | Add 21325 label for PRISM

---

CPS-0003/README.md

This is a trivial change since CPS-0003 was written long before any of its solution CIPs emerged, so discussion of those methods isn't integral to the text: we need only remove the header link.  Confirmation (or to dispute):
- https://github.com/cardano-foundation/CIPs/pull/444#pullrequestreview-2596450921
- https://github.com/cardano-foundation/CIPs/pull/944#issuecomment-2637744389

CPS-0003 | Remove deprecated candidate CIP-0143 as solution

---

CIP-0030/README.md
CIP-0030/extensions-register.md

adds link to [file with extensions table](https://github.com/Ryun1/CIPs/blob/cip30-extension-discoverability/CIP-0030/extensions-register.md).

CIP-0030 | Add register to track accepted extensions

---

CIP-0010/registry.json

We would like to register a new metadata label `1517` for the application Reeve. This application is developed by the Cardano Foundation. 
The first publication of this application can be found here: [CF Blog - Reeve](https://www.cardanofoundation.org/blog/boosting-transparency-on-chain-financial-report)
Reeve is an application, which will help organisations to publish their financial reports and transactions on-chain. 
The source code is OpenSource and the on-chain metadata format description can be found here: [cf-reeve-platform (Github)](https://github.com/cardano-foundation/cf-reeve-platform/blob/main/docs/onChainFormat.md) 
The label 1517 is chosen by the year of death of [Luca Pacioli](https://en.wikipedia.org/wiki/Luca_Pacioli) known for being an early contributor to the field of …

CIP-0010 | Adding 1517 metadata label for Reeve

---

CIP-0143/README.md
CIP-interoperable-programmable-tokens/README.md

This CIP proposes a robust framework for the issuance of interoperable programmable tokens on Cardano. Unlike all its predecessors, this framework allows these tokens to be used in existing dApps, and does not require dApps to be developed specifically for these tokens.
---
([latest version rendered from branch](https://github.com/colll78/CIPs/blob/patch-3/CIP-0143/README.md))

CIP-0143? | Interoperable Programmable Tokens

---

CIP-0010/registry.json

This label will be used to record the metadata that confirms a dApp Rating onchain.
We've just implemented a full dApp Store using base data from Cardano Cube, and we're enhancing it with the first-ever Rating system for dApps.
Along with an offchain index and average tracker, we're recording onchain the metadata related to the each users rate.
Here's a sample of the metadata that other wallets and dApps can use to show the latest rate for that dApp.
**Label: 1668** 
```
{
"type": "dapp-rating",
"uuid": "bbfc8a90-6eb4-40b8-9e02-e3a49f04da90",
"origin": "Begin Wallet",
"ratings": [
{ "logo": "https://cdn.cardanocube.com/zy9gja7hc5ouedh62i0vlzla5yxk", "name": "NMKR", "dappId": "nmkr", "rating": 5, "category": "NFT & Token Minting" },
{ "logo": …
```

CIP-0010 | Add 1668 label for Begin Wallet: dApp rating

---

CIP-0137/README.md

This PR includes updates of the [**CIP-0137**](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0137/README.md):
- The **N2C Local Message Submission mini-protocol** has been updated with a CDDL specification
- The **N2C Local Message Notification mini-protocol** has been updated with a CDDL specification
- The **N2C Local Message Notification mini-protocol** state machine has been updated to return all messages pending notification at once 
- The **Implementation plan** has been updated to reflect the achieved milestones
- The document has been linted.
---
([latest version of updated document](https://github.com/cardano-scaling/CIPs/blob/update-cip-0137/CIP-0137/README.md))

CIP-0137 | Update mini-protocols and implementation plan

---

CPS-0003/README.md

Noting, according to https://github.com/cardano-foundation/CIPs/pull/832#issuecomment-2782841005, CIP-0125's proposed functionality seems already incorporated into candidate CIP-0113 due to being encompassed by the superseded CIP-143.

CPS-0003 | Withdraw candidate CIP-0125 as solution

---

CIP-0060/README.md

The metadata in the example incorrectly used track_number as a string instead of the standard defined integer.  No changes needed to any of the other docs.

CIP-0060 | Example track_number: change string to integer

---

CPS-0021/README.md

@nhenin one thing we missed in review: the `Status:` of `Proposed` is only for CIPs which are not `Active` yet... similarly, CPSs are `Open` until they are `Solved`.
@Ryun1 @Crypto2099 we might as well give a triple check to the front matter & other features we sometimes speed read through, after the double check during the meeting today when we were trying to cover so many other discussion points concurrently.

CPS-0021 | Fix inappropriate status

---

CIP-0005/README.md

[CIP-0005](https://cips.cardano.org/cip/CIP-0005) does not specify bech32 prefixes for extended pool operator keys.
These were added to cardano-api with https://github.com/IntersectMBO/cardano-api/pull/781 and is now part of cardano-cli with https://github.com/IntersectMBO/cardano-cli/pull/1091 (addresses https://github.com/IntersectMBO/cardano-cli/issues/1076)
This PR modifies CIP-0005 to define a standard set of prefixes for them:
- `pool_xsk` for pool operator extended signing key
- `pool_xvk` for pool operator extended verification key
Other changes:
- Added [cardano-signer](https://github.com/gitmachtl/cardano-signer) to the list of tools (acceptance criteria)
- Added an entry in the `Changelog table`
- Corrected the false date of the `ID=1` entry in the `Changelog table` from `2024` …

CIP-0005 | Define bech32 prefixes for extended pool operator keys

---

CIP-0137/README.md

This PR includes updates of the [**CIP-0137**](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0137/README.md):
- Some typos have been fixed in the **N2C Local Message Notification mini-protocol**.
- Missing `KES Period` in the message has been added.
- The **Implementation plan** has been updated to reflect the achieved milestones.
---
([latest version of updated document](https://github.com/cardano-scaling/CIPs/blob/jpraynaud/update-cip-0137/CIP-0137/README.md))

CIP-0137 | Fix mini-protocols and update implementation plan 

---

.github/CIP-TEMPLATE.md
.github/CPS-TEMPLATE.md
CIP-0001/README.md
CIP-9999/README.md
README.md

A more-or-less annual update to fix/clarify these issues that came up over the last year or so (since #924):
- Don't include commits from previously submitted PR's... submit your new PR from a branch that's been rebased on `main` ([as described here](https://github.com/cardano-foundation/CIPs/pull/933#pullrequestreview-2414983753))
- Don't do "force push": with reason explained [here](https://github.com/cardano-foundation/CIPs/pull/938#issuecomment-2466654892) to someone who hadn't done it before, preemptively (in terms of usability of commit history)
- Don't put backticks in CIP titles (we had to [remove them here](https://github.com/cardano-foundation/CIPs/pull/930))
- Add `Consensus` and `Network` categories to CIP and CPS templates ([pointed out …

CIP-0001, CIP-9999, README & templates: periodic update

---

README.md

Merges from meeting 115:
* https://github.com/cardano-foundation/CIPs/pull/869
* https://github.com/cardano-foundation/CIPs/pull/798
* https://github.com/cardano-foundation/CIPs/pull/1011
* https://github.com/cardano-foundation/CIPs/pull/997
Merges carried over from meeting 114 (https://github.com/cardano-foundation/CIPs/pull/1049 not signed off in time):
* https://github.com/cardano-foundation/CIPs/pull/971

Update top-level README: post meeting 115

---

CIP-0100/cip-0100.common.schema.json
CIP-0108/cip-0108.common.schema.json
CIP-0136/cip-136.common.schema.json

- fix naming of `@type` property within CIP108 and CIP136 schemas

CIP-108 CIP-136 | Small schema fixes

---

CIP-0149/README.md

Resubmitted from https://github.com/cardano-foundation/CIPs/pull/1066 (closed due to submission from an unclean / already merged branch).
Thanks to @colll78 for spotting & fixing, with apologies for editors not noticing this significant inconsistency during the review process.  Likely the correct metric would be understandable from the context, but readers would never be sure & therefore @Ryun1 @Crypto2099 @perturbing this should be merged as top priority.

CIP-0149 | Fix reward order of magnitude

---

CIP-0152/README.md
CIP-plutus-modules/README.md

Cardano scripts are limited in complexity by the fact that each script must be supplied in one transaction, whether the script is supplied in the same transaction in which it is used, or pre-loaded onto the chain for use as a reference script. This limits script code size, which in turn limits the use of libraries in scripts, and ultimately limits the sophistication of Cardano apps, compared to competing blockchains. It is the aspect of Cardano that script developers complain about most.
This CIP addresses this problem directly, by allowing reference inputs to supply 'modules', which can be used from other scripts (including other modules), thus allowing the code of a script to be spread across many reference inputs. The 'main specification' requires no changes to UPLC, PTLC, PIR or …

CIP-0152? | Modules in UPLC
